"""Apply Reading Mode 4 integration to generated WEB files only."""
from pathlib import Path
import sys

def patch(output):
 output=Path(output)
 p=output/'app.js';s=p.read_text()
 s=s.replace("['word','tajweed','plain']","['word','tajweed','plain','study']")
 s=s.replace("const maxPages=()=>mode===", "const maxPages=()=>mode==='study'?STUDY_NAV.total:mode===")
 s=s.replace("const isScan=()=>mode==='word'||mode==='plain';", "const isScan=()=>mode==='word'||mode==='plain'||mode==='study';")
 s=s.replace("const bookmarkKey=()=>mode===", "const bookmarkKey=()=>mode==='study'?'tm-study-bookmarks':mode===")
 s=s.replace("Number(load(mode==='word'?'tm-word-page':mode==='plain'?'tm-plain-page':'tm-page',1))", "Number(load(pageKey(),mode==='study'?STUDY_NAV.first:1))")
 s=s.replace("function pageKey(){return mode===", "function pageKey(){return mode==='study'?'tm-study-page':mode===")
 s=s.replace("const modeLabel=m=>m===", "const modeLabel=m=>m==='study'?'Study the Noble Qur’an':m===")
 s=s.replace("const meta=mode==='plain'?PLAIN_NAV.headers[page]:null;", "const meta=mode==='plain'?PLAIN_NAV.headers[page]:mode==='study'?STUDY_NAV.headers[page]:null;")
 s=s.replace("$('top-label').textContent=mode==='plain'?'13-line", "$('top-label').textContent=mode==='study'?(meta.intro?'Study Qur’an · Volume '+meta.volume+' introduction':'Study Qur’an · Vol '+meta.volume+' · Juz '+meta.j):mode==='plain'?'13-line")
 s=s.replace("if(mode==='plain'&&Android.plainPage)", "if(mode==='study'&&Android.studyPage)Android.studyPage(page);else if(mode==='plain'&&Android.plainPage)")
 s=s.replace("window.receivePlainPdf=(n,data,error)=>receiveScan('plain',n,data,error);", "window.receivePlainPdf=(n,data,error)=>receiveScan('plain',n,data,error);\nwindow.receiveStudyPdf=(n,data,error)=>receiveScan('study',n,data,error);")
 s=s.replace("toast(mode==='word'?'Word-by-word pages'", "toast(mode==='study'?'Study the Noble Qur’an · Word for word':mode==='word'?'Word-by-word pages'")
 s=s.replace('Choose one of three reading modes','Choose one of four reading modes')
 s=s.replace("incoming.alt=(mode==='plain'?", "incoming.alt=(mode==='study'?'Study the Noble Qur’an, combined page ':mode==='plain'?").replace('Three offline reading modes:', 'Four reading modes:').replace('The three introductory cover/rules pages', 'The three mode-3 introductory cover/rules pages').replace('No login, advertisements, internet permission, tracking, or runtime downloads.', 'No login, advertisements or tracking. Web scans require a connection until saved for offline reading.')
 p.write_text(s)
 p=output/'adaptive.js';s=p.read_text().replace("['word','plain','tajweed']","['word','plain','tajweed','study']").replace("return prefs.layouts?.[mode]||'fill'", "return prefs.layouts?.[mode]||(mode==='study'?'width':'fill')")
 s=s.replace("clamp(prefs.pdfZooms?.[mode],100,250,100)", "clamp(prefs.pdfZooms?.[mode],100,250,mode==='study'&&window.innerWidth<600?200:100)")
 s=s.replace("['tm-plain-page',850]", "['tm-plain-page',850],['tm-study-page',STUDY_NAV.total]").replace("['tm-plain-bookmarks',850]", "['tm-plain-bookmarks',850],['tm-study-bookmarks',STUDY_NAV.total]")
 s=s.replace('(word|plain|tajweed):\\d{1,3}', '(word|plain|tajweed|study):\\d{1,4}').replace('v.pages.length>2414','v.pages.length>4211')
 s=s.replace("const canTurnGesture=()=>prefs.swipes", "const canTurnGesture=()=>!(mode==='study'&&zoomForMode()>100)&&prefs.swipes").replace("String(prefs.swipes!==false&&prefs.swipeAction!=='pan')", "String(!(mode==='study'&&zoomForMode()>100)&&prefs.swipes!==false&&prefs.swipeAction!=='pan')")
 p.write_text(s)
 p=output/'web-bridge.js';s=p.read_text().replace('word:0,plain:0','word:0,plain:0,study:0').replace("target==='word'?'receivePdf':'receivePlainPdf'", "target==='study'?'receiveStudyPdf':target==='word'?'receivePdf':'receivePlainPdf'")
 s=s.replace(' plainPage(n){', " studyPage(n){setTimeout(()=>browserScan('study',n),0)},\n plainPage(n){")
 p.write_text(s)
 p=output/'web-reader.js';s=p.read_text().replace("WEB_VERSION='2.0'", "WEB_VERSION='3.0'").replace("['word','plain','tajweed']", "['word','plain','tajweed','study']").replace('word:960,plain:850,tajweed:604','word:960,plain:850,tajweed:604,study:STUDY_NAV.total').replace('all three modes','all four modes')
 p.write_text(s)
 p=output/'web-install.js';s=p.read_text().replace("[['word',1,960],['plain',1,850]]", "[['word',1,960],['plain',1,850],['study',1,STUDY_NAV.total]]").replace("mode==='word'?WORD_NAV:PLAIN_NAV", "mode==='study'?STUDY_NAV:mode==='word'?WORD_NAV:PLAIN_NAV").replace('saved={word:0,plain:0}', 'saved={word:0,plain:0,study:0}').replace('(word|plain)-', '(word|plain|study)-')
 s=s.replace('Plain Tajweed: ${saved.plain}/850 pages.', 'Plain Tajweed: ${saved.plain}/850 pages · Study Qur’an: ${saved.study}/${STUDY_NAV.total} pages.')
 s=s.replace('Save complete Qur’an · about 210 MB', 'Save all scanned modes · about ${Math.ceil(210+STUDY_PDF.pageBytes/1048576)} MB')
 p.write_text(s)
 p=output/'sw.js';s=p.read_text().replace("quran-shell-v2", "quran-shell-v3").replace("'web-reader.js',", "'web-reader.js','web-study.js','study-navigation.js','study-meta.js','study-download.js',")
 # PDF chunks bypass shell caching; download validates each chunk explicitly.
 s=s.replace(" if(u.pathname.includes('/pages/'))", " if(u.pathname.includes('/study-pdf/')){e.respondWith(fetch(e.request));return}\n if(u.pathname.includes('/pages/'))")
 p.write_text(s)
 p=output/'index.html';s=p.read_text().replace('<script src="web-bridge.js">','<script src="study-navigation.js"></script><script src="study-meta.js"></script><script src="study-download.js"></script><script src="web-bridge.js">').replace('</body>','<script src="web-study.js"></script></body>');p.write_text(s)
if __name__=='__main__':patch(sys.argv[1])
