'use strict';
let webWorkerReady;
if('serviceWorker' in navigator)webWorkerReady=navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).catch(()=>null);
const PAGE_CACHE='quran-pages-v1';let offlineJob=null;
const scanUrl=(m,n)=>`pages/${m}-${n}.${SCANS[m][n-1].ext}`;
function downloadRange(kind){if(kind==='all')return [['word',1,960],['plain',1,850]];if(mode==='tajweed')return [];if(kind==='mode')return [[mode,1,maxPages()]];const nav=mode==='word'?WORD_NAV:PLAIN_NAV,list=kind==='surah'?nav.surahs:nav.juz;const current=[...list].reverse().find(s=>s.page<=page)||list[0],index=list.indexOf(current),end=list[index+1]?.page||maxPages()+1;return [[mode,current.page,Math.max(current.page,end-1)]]}
async function offlineOverview(){const cache=await caches.open(PAGE_CACHE),keys=await cache.keys(),saved={word:0,plain:0};for(const k of keys){const match=new URL(k.url).pathname.match(/\/pages\/(word|plain)-\d+\./);if(match)saved[match[1]]++}return saved}
function offlineProgress(){const text=$('offline-status'),bar=$('offline-progress');if(!text||!offlineJob)return;text.textContent=offlineJob.message||`Saved ${offlineJob.done} of ${offlineJob.total} selected pages. Keep the app open.`;if(bar){bar.max=offlineJob.total||1;bar.value=offlineJob.done}}
async function startOfflineDownload(kind){
 if(offlineJob?.running)return;
 const queue=downloadRange(kind).flatMap(([m,a,b])=>Array.from({length:b-a+1},(_,i)=>[m,a+i]));
 const job=offlineJob={running:true,done:0,total:queue.length,controller:new AbortController(),paused:false,message:''};offlineScreen();
 try{const ready=await webWorkerReady;if(!ready)throw Error('Offline setup is unavailable. Reload while online and try again.');const cache=await caches.open(PAGE_CACHE);let index=0;
 const worker=async()=>{while(index<queue.length&&!job.controller.signal.aborted){const [m,n]=queue[index++],url=scanUrl(m,n);if(!await cache.match(url)){let response;for(let attempt=0;attempt<3;attempt++){try{response=await fetch(url,{signal:job.controller.signal});if(!response.ok||!response.headers.get('content-type')?.startsWith('image/'))throw Error('Could not download a page. Check your connection.');break}catch(e){if(job.controller.signal.aborted||attempt===2)throw e}}await cache.put(url,response)}job.done++;offlineProgress()}};
 let firstError;const guarded=()=>worker().catch(e=>{firstError??=e;job.controller.abort();throw e});await Promise.allSettled([guarded(),guarded()]);if(firstError)throw firstError;job.message=job.paused?'Paused. Saved pages are kept. Select the same download to resume.':'Selected pages saved. Browser storage may still be cleared by your device.';await navigator.storage?.persist?.();
 }catch(e){job.message=job.paused?'Paused. Saved pages are kept.':e.name==='QuotaExceededError'?'Storage is full. Saved pages are kept; free space or choose a smaller download.':e.message;job.controller.abort()}
 finally{job.running=false;offlineProgress();const pause=$('cancel-download');if(pause)pause.classList.add('hidden');document.querySelectorAll('[data-download]').forEach(b=>b.disabled=false);await updateOfflineCounts()}
}
async function updateOfflineCounts(){const node=$('offline-counts');if(!node)return;try{const saved=await offlineOverview(),estimate=await navigator.storage?.estimate?.();if(node.isConnected)node.textContent=`Word by word: ${saved.word}/960 pages · Plain Tajweed: ${saved.plain}/850 pages.`+(estimate?.quota?` Browser storage: ${Math.round((estimate.usage||0)/1048576)} MB used of ${Math.round(estimate.quota/1048576)} MB quota.`:'')}catch{node.textContent='Saved-page counts are unavailable.'}}
function offlineScreen(){openSheet('Offline reading',`<p class="helper">Mode 2 text and meanings are saved with the app. Choose how much to save for the scanned modes. Downloads resume by skipping saved pages.</p><p id="offline-counts" class="helper">Checking saved pages…</p><p id="offline-status" role="status" aria-live="polite"></p><progress id="offline-progress" max="1" value="0" aria-label="Download progress"></progress><div class="tools-actions">${mode!=='tajweed'?'<button data-download="surah">Save current Surah</button><button data-download="juz">Save current Juz</button><button data-download="mode">Save this reading mode</button>':''}<button class="action" data-download="all">Save complete Qur’an · about 210 MB</button><button id="cancel-download" ${offlineJob?.running?'':'class="hidden"'}>Pause download</button></div><p class="helper">Keep the app open until finished. Safari may remove offline files when storage is low. Bookmarks and settings are stored separately on this device.</p>`);
 if(!('caches' in window)){$('offline-status').textContent='Offline storage is unavailable. Use Safari outside private browsing.';document.querySelectorAll('[data-download]').forEach(b=>b.disabled=true);return}document.querySelectorAll('[data-download]').forEach(b=>{b.disabled=!!offlineJob?.running;b.onclick=()=>startOfflineDownload(b.dataset.download)});$('cancel-download').onclick=()=>{if(offlineJob){offlineJob.paused=true;offlineJob.controller.abort()}};offlineProgress();updateOfflineCounts()}
const webDrawer=drawer;drawer=function(){webDrawer();const bottom=$('drawer').querySelector('.drawer-bottom');bottom.innerHTML='Complete Qur’an · Save pages for offline reading<br>No advertisements';bottom.insertAdjacentHTML('beforebegin','<button class="drawer-row" id="web-offline"><span class="icon">↓</span>Save for offline reading</button>');$('web-offline').onclick=offlineScreen};
$('menu').onclick=drawer;if($('focus-menu'))$('focus-menu').onclick=drawer;
if(!navigator.standalone&&!matchMedia('(display-mode: standalone)').matches&&!load('tm-install-tip',false)){const tip=document.createElement('div');tip.id='install-tip';tip.innerHTML='<button aria-label="Dismiss installation tip">×</button><strong>Read from your Home Screen</strong><br>On iPad or iPhone: open in Safari, tap Share, then Add to Home Screen.';document.body.appendChild(tip);tip.querySelector('button').onclick=()=>{save('tm-install-tip',true);tip.remove()}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&prefs.awake)Android.awake(true)});
const browserScreen=screen;screen=function(id){browserScreen(id);if(id==='settings'){for(const id of ['word-quality','volume']){const control=$(id);if(control)control.closest('.setting').classList.add('hidden')}}};
