'use strict';
const WEB_VERSION='2.0';
const ayahMarks=()=>load('tm-web-ayah-marks',[]);
const pageLink=(m=mode,n=page,s,a)=>{const u=new URL(location.href);u.hash=new URLSearchParams({mode:m,page:n,...(s&&a?{surah:s,ayah:a}:{})}).toString();return u.href};
async function shareReading(s,a){const url=pageLink(mode,page,s,a);try{if(navigator.share){await navigator.share({title:'Tajweed & Meaning',url});return}if(navigator.clipboard){await navigator.clipboard.writeText(url);toast('Reading link copied');return}}catch(e){if(e.name==='AbortError')return}openSheet('Share this reading',`<p class="helper">Copy this link to open the same ${s?'ayah':'page'}.</p><input id="reading-link" class="search" readonly aria-label="Reading link"><button class="action" id="select-link">Select link</button>`);$('reading-link').value=url;$('select-link').onclick=()=>{$('reading-link').focus();$('reading-link').select()}}
function openAyah(s,a){const p=Object.keys(QURAN.pages).find(p=>QURAN.pages[p].some(v=>v.s===s&&v.a===a));if(!p)return;changeMode('tajweed');go(Number(p),s,a)}
function toggleAyahMark(s,a){const list=ayahMarks(),i=list.findIndex(v=>v.s===s&&v.a===a);if(i>=0)list.splice(i,1);else list.push({s,a});save('tm-web-ayah-marks',list);decorateAyahs();toast(i>=0?'Ayah bookmark removed':'Ayah bookmarked')}
function decorateAyahs(){if(mode!=='tajweed')return;document.querySelectorAll('.verse').forEach(node=>{if(node.querySelector('.ayah-actions'))return;const [,s,a]=node.id.split('-').map(Number);const box=document.createElement('div');box.className='ayah-actions';box.innerHTML=`<button aria-label="Bookmark ayah ${s}:${a}" aria-pressed="${ayahMarks().some(v=>v.s===s&&v.a===a)}">☆ Save ayah</button><button aria-label="Share ayah ${s}:${a}">Share ${s}:${a}</button>`;box.children[0].onclick=e=>{e.stopPropagation();toggleAyahMark(s,a);e.currentTarget.setAttribute('aria-pressed',String(ayahMarks().some(v=>v.s===s&&v.a===a)))};box.children[1].onclick=e=>{e.stopPropagation();shareReading(s,a)};node.appendChild(box)})}
const webRender=render;render=function(){webRender();decorateAyahs()};decorateAyahs();
function readingTools(){openSheet('Reading tools',`${isScan()?'<div class="setting"><label for="quick-zoom">Page magnification</label><select id="quick-zoom">'+[100,125,150,175,200,250].map(v=>`<option value="${v}" ${zoomForMode()===v?'selected':''}>${v}%</option>`).join('')+'</select></div><p class="helper">At larger sizes, scroll the page or use Word-by-word study. Original scan detail is preserved.</p>':`<div class="setting"><label for="quick-arabic">Arabic text size</label><input id="quick-arabic" type="range" min="30" max="72" value="${prefs.size||36}"></div><div class="setting"><label for="quick-english">Meaning text size</label><input id="quick-english" type="range" min="16" max="36" value="${prefs.englishSize||20}"></div>`}<div class="tools-actions"><button id="quick-night">${prefs.dark?'Light':'Night'} controls</button><button id="quick-focus">Full-page reading</button><button id="quick-share">Share this page</button><button id="quick-saved">Saved ayahs</button></div><p class="helper">Your choices stay on this device. Web reader ${WEB_VERSION}.</p>`);
 if(isScan())$('quick-zoom').onchange=()=>{prefs.pdfZooms={...(prefs.pdfZooms||{}),[mode]:Number($('quick-zoom').value)};lastZoomPosition='';applyPrefs()};else for(const [id,key] of [['quick-arabic','size'],['quick-english','englishSize']])$(id).oninput=()=>{prefs[key]=Number($(id).value);applyPrefs()};
 $('quick-night').onclick=()=>{prefs.dark=!prefs.dark;applyPrefs();readingTools()};$('quick-focus').onclick=()=>{closePanels();fullscreen(true)};$('quick-share').onclick=()=>shareReading();$('quick-saved').onclick=showAyahMarks;
}
function showAyahMarks(){const list=ayahMarks();openSheet('Saved ayahs',list.length?list.map((v,i)=>`<div class="list-row"><button class="names" data-ayah="${i}">${esc(QURAN.surahs[v.s-1].name)} ${v.s}:${v.a}</button><button data-delete-ayah="${i}" aria-label="Remove ayah bookmark">×</button></div>`).join(''):'<p class="helper">In mode 2, use Save ayah beneath a verse. Page bookmarks in all three modes remain available in Bookmarks.</p>');document.querySelectorAll('[data-ayah]').forEach(b=>b.onclick=()=>{const v=list[Number(b.dataset.ayah)];openAyah(v.s,v.a)});document.querySelectorAll('[data-delete-ayah]').forEach(b=>b.onclick=()=>{list.splice(Number(b.dataset.deleteAyah),1);save('tm-web-ayah-marks',list);showAyahMarks()})}
const readerDrawer=drawer;drawer=function(){readerDrawer();const bottom=$('drawer').querySelector('.drawer-bottom');bottom.insertAdjacentHTML('beforebegin','<button class="drawer-row" id="web-reading-tools"><span class="icon">Aa</span>Reading tools</button><button class="drawer-row" id="web-saved-ayahs"><span class="icon">☆</span>Saved ayahs</button><button class="drawer-row" id="web-share"><span class="icon">↗</span>Share current page</button>');$('web-reading-tools').onclick=readingTools;$('web-saved-ayahs').onclick=showAyahMarks;$('web-share').onclick=()=>shareReading()};$('menu').onclick=drawer;if($('focus-menu'))$('focus-menu').onclick=drawer;
backupKeys.push('tm-web-ayah-marks','tm-web-position');
const webValidate=validateBackup;validateBackup=function(b){webValidate(b);const list=b.data['tm-web-ayah-marks'];if(list!=null&&(!Array.isArray(list)||list.length>6236||list.some(v=>!Number.isInteger(v.s)||v.s<1||v.s>114||!Number.isInteger(v.a)||v.a<1||v.a>QURAN.surahs[v.s-1].count)))throw Error('Invalid ayah bookmarks');const p=b.data['tm-web-position'];if(p!=null&&(!['word','plain','tajweed'].includes(p.mode)||!Number.isInteger(p.page)||p.page<1||p.page>({word:960,plain:850,tajweed:604}[p.mode])||![p.top,p.left].every(v=>Number.isFinite(v)&&v>=0)))throw Error('Invalid reading position')};
function rememberPosition(){const stage=isScan()?$('pdf-stage'):$('reader');if(stage)save('tm-web-position',{mode,page,top:Math.max(0,stage.scrollTop),left:Math.max(0,stage.scrollLeft)})}
let pendingPosition=load('tm-web-position',null),positionTimer;
$('reader').addEventListener('scroll',()=>{clearTimeout(positionTimer);positionTimer=setTimeout(rememberPosition,250)},{capture:true,passive:true});
window.addEventListener('pagehide',rememberPosition);
function restorePosition(){if(!pendingPosition||pendingPosition.mode!==mode||pendingPosition.page!==page)return;const stage=isScan()?$('pdf-stage'):$('reader');if(!stage||(isScan()&&!$('pdf-image')?.naturalWidth))return;const p=pendingPosition;pendingPosition=null;setTimeout(()=>{stage.scrollTop=p.top;stage.scrollLeft=p.left},80)}
new MutationObserver(()=>{decorateAyahs();restorePosition()}).observe($('page'),{childList:true,subtree:true});
$('page').addEventListener('load',restorePosition,true);document.fonts.ready.then(restorePosition);
function followReadingLink(){const args=new URLSearchParams(location.hash.slice(1)),m=args.get('mode'),n=Number(args.get('page'));if(!['word','plain','tajweed'].includes(m)||!Number.isInteger(n)||n<(m==='plain'?4:1)||n>({word:960,plain:850,tajweed:604}[m]))return;pendingPosition=null;changeMode(m);const s=Number(args.get('surah')),a=Number(args.get('ayah'));if(m==='tajweed'&&s>=1&&s<=114&&Number.isInteger(a)&&a>=1&&a<=QURAN.surahs[s-1].count)openAyah(s,a);else go(n)}
window.addEventListener('hashchange',followReadingLink);if(location.hash)followReadingLink();
let sheetFocus=null;const accessibleSheet=openSheet;openSheet=function(title,html){const focus=document.activeElement;accessibleSheet(title,html);sheetFocus=focus;$('sheet').setAttribute('role','dialog');$('sheet').setAttribute('aria-modal','true');$('sheet').setAttribute('aria-label',title);requestAnimationFrame(()=>($('sheet').querySelector('input:not([readonly]),textarea')||$('sheet-back'))?.focus())};
document.addEventListener('keydown',e=>{const sheet=$('sheet');if(e.key==='Escape'){e.preventDefault();closePanels();sheetFocus?.isConnected&&sheetFocus.focus?.();return}if(e.key==='Tab'&&!sheet.classList.contains('hidden')){const items=[...sheet.querySelectorAll('button:not([disabled]),input:not([disabled]),select,textarea,a[href]')].filter(el=>!el.closest('.hidden'));if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
if(matchMedia('(prefers-reduced-motion: reduce)').matches&&prefs.motion===undefined){prefs.motion=false;applyPrefs()}
