// Extend the supplied v1.7 reader; never resize its Arabic or English to fit.
const modesButton=document.createElement('button');
modesButton.id='modes-button';modesButton.setAttribute('aria-label','Reading modes');modesButton.title='Reading modes';modesButton.textContent='▣';
modesButton.onclick=()=>screen('modes');document.querySelector('header').insertBefore(modesButton,$('bookmark'));
const progressBar=document.createElement('div');progressBar.id='reading-progress';document.querySelector('footer').appendChild(progressBar);
const clamp=(n,min,max,fallback)=>Number.isFinite(Number(n))?Math.min(max,Math.max(min,Number(n))):fallback;
const layoutChoices=[['fill','v1.7 full page (default)'],['proportions','Original proportions'],['width','Fit width and scroll'],['cover','Crop to fill (edges may be hidden)']];
if(load('tm-adaptive-layout',0)<2){prefs.layouts={word:'fill',plain:'fill'};prefs.pdfFit='fill';save('tm-adaptive-layout',2)}
function layoutForMode(){return prefs.layouts?.[mode]||'fill'}
function readerAppearance(){
 document.body.dataset.pdfLayout=layoutForMode();document.body.classList.toggle('large-controls',!!prefs.largeControls);document.body.classList.toggle('no-progress',prefs.progress===false);
 document.documentElement.style.setProperty('--reading-line',clamp(prefs.readingLine,1.5,2.8,1.9));
 document.documentElement.style.setProperty('--meaning-line',clamp(prefs.meaningLine,1.3,2.2,1.65));
 document.documentElement.style.setProperty('--page-brightness',clamp(prefs.brightness,50,100,100)/100);
 progressBar.style.width=((page-minPage()+1)/(maxPages()-minPage()+1)*100)+'%';
 if(window.Android&&Android.appearance)Android.appearance(document.body.classList.contains('dark'));
}
const adaptivePrefs=applyPrefs;applyPrefs=function(){adaptivePrefs();readerAppearance()};
let lastReadingPosition=mode+':'+page;
const adaptiveRender=render;render=function(){adaptiveRender();readerAppearance();recordReadingPage();const key=mode+':'+page;if(key!==lastReadingPosition){const stage=$('pdf-stage');if(stage)stage.scrollTop=0;lastReadingPosition=key}};
const originalReaderTap=reader.onclick;reader.onclick=e=>{if(prefs.tapControls!==false)originalReaderTap(e)};
// Keyboard support also works with tablets and external keyboards; follows Arabic page order.
document.addEventListener('keydown',e=>{if(!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&$('sheet').classList.contains('hidden')&&$('drawer').classList.contains('hidden')){if(e.key==='ArrowRight'){e.preventDefault();go(page+1)}else if(e.key==='ArrowLeft'){e.preventDefault();go(page-1)}}});
let readingStats=load('tm-reading-stats',{days:{}});
const todayKey=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
function dayStats(){const key=todayKey();if(!readingStats.days[key])readingStats.days[key]={seconds:0,pages:[]};return readingStats.days[key]}
function persistStats(){const keys=Object.keys(readingStats.days).sort();while(keys.length>366)delete readingStats.days[keys.shift()];save('tm-reading-stats',readingStats)}
function recordReadingPage(){const d=dayStats(),key=mode+':'+page;if(!d.pages.includes(key)){d.pages.push(key);persistStats()}}
// Count foreground reading time only, excluding navigation screens and long background gaps.
let lastTick=Date.now();setInterval(()=>{const now=Date.now(),seconds=Math.min(15,Math.max(0,(now-lastTick)/1000));lastTick=now;if(document.visibilityState==='visible'&&$('sheet').classList.contains('hidden')&&$('drawer').classList.contains('hidden')){dayStats().seconds+=seconds;persistStats()}},15000);
document.addEventListener('visibilitychange',()=>{lastTick=Date.now()});
const toolsDrawer=drawer;drawer=function(){toolsDrawer();const bottom=$('drawer').querySelector('.drawer-bottom');[['note','✎','Bookmark note'],['stats','◷','Reading goals & statistics'],['backup','⇄','Backup & restore']].forEach(([id,icon,label])=>{const b=document.createElement('button');b.className='drawer-row';b.innerHTML='<span class="icon">'+icon+'</span>'+label;b.onclick=()=>screen(id);bottom.before(b)})};$('menu').onclick=drawer;
function selectSetting(id,title,options,value,help=''){return `<div class="setting"><label for="${id}">${title}<small>${help}</small></label><select id="${id}">${options.map(([v,t])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${t}</option>`).join('')}</select></div>`}
function checkSetting(id,title,value,help=''){return `<div class="setting"><label for="${id}">${title}<small>${help}</small></label><input type="checkbox" id="${id}" ${value?'checked':''}></div>`}
const toolsScreen=screen;screen=function(id){
 if(id==='note'){const key=mode+':'+page,notes=load('tm-bookmark-notes',{});openSheet('Bookmark note',`<p class="helper">${esc(modeLabel(mode))} · Page ${page}. Saving adds a bookmark.</p><textarea class="note-text" id="note-text" maxlength="2000" aria-label="Bookmark note">${esc(notes[key]||'')}</textarea><div class="tools-actions"><button class="action" id="save-note">Save note & bookmark</button><button id="remove-note">Remove note</button></div>`);$('save-note').onclick=()=>{notes[key]=$('note-text').value.trim();save('tm-bookmark-notes',notes);if(!marks.includes(page)){marks.push(page);marks.sort((a,b)=>a-b);save(bookmarkKey(),marks);updateBookmark()}toast('Note saved');closePanels()};$('remove-note').onclick=()=>{delete notes[key];save('tm-bookmark-notes',notes);toast('Note removed');closePanels()};return}
 if(id==='stats'){const d=dayStats(),goal=clamp(prefs.goal,1,120,10),total=Object.values(readingStats.days).reduce((n,d)=>n+d.seconds,0);openSheet('Reading goals & statistics',`<div class="tools-grid"><div class="stat-card"><strong>${d.pages.length} / ${goal}</strong>Unique pages today</div><div class="stat-card"><strong>${Math.floor(d.seconds/60)}</strong>Reading minutes today</div><div class="stat-card"><strong>${Math.floor(total/60)}</strong>Total reading minutes</div><div class="stat-card"><strong>${Object.keys(readingStats.days).length}</strong>Reading days recorded</div></div><p class="helper">Pages are counted once per mode each day. Time counts while the reader is visible. Statistics stay on this device. A daily goal is a personal reminder.</p>${selectSetting('daily-goal','Daily page goal',[1,5,10,15,20,30,60,120].map(n=>[n,n+' pages']),goal)}`);$('daily-goal').onchange=()=>{prefs.goal=Number($('daily-goal').value);applyPrefs()};return}
 if(id==='backup'){openBackup();return}
 toolsScreen(id);
 if(id==='bookmarks'){const notes=load('tm-bookmark-notes',{});$('sheet').querySelectorAll('[data-page]').forEach(b=>{const note=notes[mode+':'+b.dataset.page];if(note){const el=document.createElement('small');el.textContent=note;b.appendChild(el)}});return}
 if(id!=='settings')return;
 const content=$('sheet').querySelector('.sheet-content');
 const fit=$('pdf-fit');fit.innerHTML=layoutChoices.map(([v,t])=>`<option value="${v}" ${layoutForMode()===v?'selected':''}>${t}</option>`).join('');fit.onchange=()=>{prefs.layouts={...(prefs.layouts||{}),[mode]:fit.value};prefs.pdfFit=fit.value;applyPrefs()};fit.previousElementSibling.innerHTML='PDF page layout<small>Saved separately for each PDF mode. Default matches v1.7. Fit width scrolls without shrinking or stretching text.</small>';if(mode==='tajweed')fit.closest('.setting').classList.add('hidden');
 content.insertAdjacentHTML('beforeend',checkSetting('large-controls','Larger toolbar controls',!!prefs.largeControls,'Optional extra height; standard controls maximize page space.')+checkSetting('tap-controls','Tap page to hide/show bars',prefs.tapControls!==false,'Disable if accidental taps interrupt reading. The fullscreen button still works.')+checkSetting('show-progress','Page progress indicator',prefs.progress!==false)+selectSetting('reading-line','Arabic line spacing',[1.7,1.9,2.2,2.5].map(n=>[n,n]),prefs.readingLine||1.9,'Colour Tajweed with meaning only; PDF text stays unchanged.')+selectSetting('meaning-line','English line spacing',[1.4,1.65,1.9,2.1].map(n=>[n,n]),prefs.meaningLine||1.65)+`<div class="setting"><label for="page-brightness">Reading dimmer<small>Dims only the reading page; does not change phone brightness.</small></label><input type="range" min="50" max="100" step="5" id="page-brightness" value="${clamp(prefs.brightness,50,100,100)}" aria-label="Reading brightness"></div>`+selectSetting('daily-goal','Daily page goal',[1,5,10,15,20,30,60,120].map(n=>[n,n+' pages']),prefs.goal||10)+`<div class="tools-actions"><button class="action" id="reading-stats">Reading statistics</button><button id="reading-backup">Backup / restore</button><button id="reset-reading">Reset display settings</button></div><p class="helper">All reading tools work offline. Reset display keeps bookmarks, notes, last-read pages and statistics.</p>`);
 [['large-controls','largeControls'],['tap-controls','tapControls'],['show-progress','progress']].forEach(([id,key])=>$(id).onchange=()=>{prefs[key]=$(id).checked;applyPrefs()});
 [['reading-line','readingLine'],['meaning-line','meaningLine'],['daily-goal','goal']].forEach(([id,key])=>$(id).onchange=()=>{prefs[key]=Number($(id).value);applyPrefs()});
 $('page-brightness').oninput=()=>{prefs.brightness=Number($('page-brightness').value);applyPrefs()};$('reading-stats').onclick=()=>screen('stats');$('reading-backup').onclick=()=>screen('backup');
 $('reset-reading').onclick=()=>{prefs={meaning:true,dark:false,size:36,englishSize:20,awake:false,wordTheme:'cream',pdfFit:'fill',layouts:{word:'fill',plain:'fill'},motion:true};applyPrefs();screen('settings');toast('Display settings reset')};
 if(!(window.Android&&Android.volumeKeys))$('volume')?.closest('.setting').classList.add('hidden');
};
const backupKeys=['tm-settings','tm-mode','tm-page','tm-word-page','tm-plain-page','tm-bookmarks','tm-word-bookmarks','tm-plain-bookmarks','tm-bookmark-notes','tm-reading-stats'];
function openBackup(){const data={format:'tajweed-meaning-backup',version:1,data:Object.fromEntries(backupKeys.map(k=>[k,load(k,null)]))};openSheet('Backup & restore',`<p class="helper">Copy this text to a safe place to back up settings, bookmarks, notes and last-read pages. To restore, paste a backup here. Restore replaces the matching data on this app; it does not import from the separate v1.7 app automatically.</p><textarea id="backup-text" class="backup-text" aria-label="Reading data backup"></textarea><div class="tools-actions"><button class="action" id="copy-backup">Select backup text</button><button id="restore-backup">Restore pasted backup</button></div><p class="helper" id="backup-status" role="status"></p>`);$('backup-text').value=JSON.stringify(data,null,2);$('copy-backup').onclick=()=>{$('backup-text').focus();$('backup-text').select();$('backup-status').textContent='Text selected. Use your phone’s Copy action, then save it somewhere safe.'};$('restore-backup').onclick=()=>{try{const text=$('backup-text').value;if(text.length>2000000)throw Error('Backup is too large');const b=JSON.parse(text);validateBackup(b);backupKeys.forEach(k=>{if(b.data[k]!=null)save(k,b.data[k])});location.reload()}catch(e){$('backup-status').textContent='Backup not restored: '+e.message}}}
function validateBackup(b){if(b?.format!=='tajweed-meaning-backup'||b.version!==1||!b.data||typeof b.data!=='object')throw Error('Unrecognized backup');const d=b.data;if(d['tm-mode']!=null&&!['word','plain','tajweed'].includes(d['tm-mode']))throw Error('Invalid reading mode');for(const [key,max]of [['tm-page',604],['tm-word-page',960],['tm-plain-page',850]])if(d[key]!=null&&(!Number.isInteger(d[key])||d[key]<1||d[key]>max))throw Error('Invalid page');for(const [key,max]of [['tm-bookmarks',604],['tm-word-bookmarks',960],['tm-plain-bookmarks',850]])if(d[key]!=null&&(!Array.isArray(d[key])||d[key].length>max||d[key].some(n=>!Number.isInteger(n)||n<1||n>max)))throw Error('Invalid bookmarks');const p=d['tm-settings'];if(p!=null){if(typeof p!=='object'||Array.isArray(p))throw Error('Invalid settings');for(const k of ['size','englishSize','brightness','goal','readingLine','meaningLine','guidePosition','warmth'])if(p[k]!=null&&(typeof p[k]!=='number'||!Number.isFinite(p[k])||p[k]<(k==='warmth'?0:1)||p[k]>120))throw Error('Invalid setting');for(const k of ['meaning','dark','awake','motion','volume','largeControls','tapControls','progress','startFocus','focusTools','swipes','guide','plainFullscreen','plainMinimal','plainFooter'])if(p[k]!=null&&typeof p[k]!=='boolean')throw Error('Invalid switch');if(p.contrast!=null&&(!Number.isFinite(p.contrast)||p.contrast<90||p.contrast>140))throw Error('Invalid contrast');if(p.pdfZooms&&Object.values(p.pdfZooms).some(v=>!Number.isFinite(v)||v<100||v>250))throw Error('Invalid magnification');if(p.layouts&&Object.values(p.layouts).some(v=>!layoutChoices.some(([k])=>k===v)))throw Error('Invalid layout')}
 const notes=d['tm-bookmark-notes'];if(notes!=null&&(typeof notes!=='object'||Array.isArray(notes)||Object.entries(notes).some(([k,v])=>! /^(word|plain|tajweed):\d{1,3}$/.test(k)||typeof v!=='string'||v.length>2000)))throw Error('Invalid notes');const stats=d['tm-reading-stats'];if(stats!=null&&(!stats.days||typeof stats.days!=='object'||Array.isArray(stats.days)||Object.entries(stats.days).some(([k,v])=>!/^\d{4}-\d{2}-\d{2}$/.test(k)||!v||!Number.isFinite(v.seconds)||v.seconds<0||!Array.isArray(v.pages)||v.pages.length>2414||v.pages.some(x=>typeof x!=='string'||!/^(word|plain|tajweed):\d{1,3}$/.test(x)))))throw Error('Invalid statistics');}
applyPrefs();recordReadingPage();readerAppearance();
// Comfortable reading tools sit above the existing renderer: the Qur'an content stays unchanged.
const focusTop=document.createElement('div');focusTop.className='focus-tools';focusTop.innerHTML='<button id="focus-menu" aria-label="Open reading menu">☰</button><button id="focus-modes" aria-label="Change reading mode">▣</button><button id="focus-bookmark" aria-label="Bookmark in focus view">☆</button><button id="focus-exit" aria-label="Show full toolbar">↙</button>';
const focusBottom=document.createElement('div');focusBottom.className='focus-bottom';focusBottom.innerHTML='<button id="focus-next" aria-label="Next page in focus view">‹</button><button id="focus-page" class="focus-page" aria-label="Go to page in focus view"></button><button id="focus-previous" aria-label="Previous page in focus view">›</button>';
document.body.append(focusTop,focusBottom);$('focus-menu').onclick=drawer;$('focus-modes').onclick=()=>screen('modes');$('focus-bookmark').onclick=bookmark;$('focus-exit').onclick=()=>fullscreen(false);$('focus-next').onclick=()=>go(page+1);$('focus-previous').onclick=()=>go(page-1);$('focus-page').onclick=()=>screen('jump');
const guide=document.createElement('div');guide.id='reading-guide';reader.appendChild(guide);
const comfortAppearance=readerAppearance;readerAppearance=function(){comfortAppearance();document.body.classList.toggle('hide-focus-tools',prefs.focusTools===false);document.body.classList.toggle('show-guide',!!prefs.guide);document.documentElement.style.setProperty('--guide-position',clamp(prefs.guidePosition,10,90,50)+'%');document.documentElement.style.setProperty('--page-contrast',clamp(prefs.contrast,90,140,100)/100);document.documentElement.style.setProperty('--page-warmth',clamp(prefs.warmth,0,30,0)/100);const bounds=reader.getBoundingClientRect();guide.style.position='fixed';guide.style.top=(bounds.top+bounds.height*clamp(prefs.guidePosition,10,90,50)/100)+'px';guide.style.left=bounds.left+'px';guide.style.right=(innerWidth-bounds.right)+'px';$('focus-page').textContent=page+' / '+maxPages();$('focus-next').disabled=page===maxPages();$('focus-previous').disabled=page===minPage();$('focus-bookmark').textContent=marks.includes(page)?'★':'☆';$('focus-bookmark').setAttribute('aria-label',marks.includes(page)?'Remove bookmark in focus view':'Bookmark in focus view')};
const focusBookmark=updateBookmark;updateBookmark=function(){focusBookmark();$('focus-bookmark').textContent=marks.includes(page)?'★':'☆';$('focus-bookmark').setAttribute('aria-label',marks.includes(page)?'Remove bookmark in focus view':'Bookmark in focus view')};
reader.addEventListener('touchend',e=>{if(prefs.swipes===false&&touch){const moved=e.changedTouches.length&&Math.abs(e.changedTouches[0].clientX-touch.x)>15;if(moved)suppressClickUntil=Date.now()+500;touch=null;e.stopImmediatePropagation()}},{capture:true,passive:true});
const comfortDrawer=drawer;drawer=function(){comfortDrawer();const b=document.createElement('button');b.className='drawer-row';b.innerHTML='<span class="icon">☼</span>Reading comfort';b.onclick=()=>screen('comfort');$('drawer').querySelector('.drawer-bottom').before(b)};$('menu').onclick=drawer;$('focus-menu').onclick=drawer;
function rangeSetting(id,title,value,min,max,step,help){return `<div class="setting"><label for="${id}">${title}<small>${help}</small></label><input type="range" id="${id}" min="${min}" max="${max}" step="${step}" value="${value}" aria-label="${title}"></div>`}
const comfortScreen=screen;screen=function(id){
 if(id==='comfort'){openSheet('Reading comfort',`<p class="helper">Choose a starting point, then fine-tune it in Settings. The text, translation and Tajweed markings are never rewritten.</p><button class="comfort-card" id="comfort-original"><strong>Original v1.7</strong><small>Full-page PDF · soft cream · original readable text sizes</small></button><button class="comfort-card" id="comfort-large"><strong>Larger, relaxed reading</strong><small>Fit-width PDFs with scrolling · larger Arabic and English in mode 2 · more line spacing</small></button><button class="comfort-card" id="comfort-night"><strong>Quiet evening</strong><small>Dark controls · dimmed pages · neutral word-by-word paper</small></button><button class="comfort-card" id="comfort-focus"><strong>Full-page focus</strong><small>Remove the full toolbars. Safe floating controls keep menu, modes, bookmarks and page turns available.</small></button><button class="action" id="comfort-settings">Fine-tune in Settings</button>`);
 const preset=(values)=>{prefs={...prefs,...values};applyPrefs();render();closePanels();toast('Reading comfort applied')};
 $('comfort-original').onclick=()=>preset({layouts:{word:'fill',plain:'fill'},pdfFit:'fill',size:36,englishSize:20,wordTheme:'cream',dark:false,brightness:100,contrast:100,warmth:0,readingLine:1.9,meaningLine:1.65,largeControls:false,guide:false});
 $('comfort-large').onclick=()=>preset({layouts:{word:'width',plain:'width'},pdfFit:'width',size:46,englishSize:24,readingLine:2.2,meaningLine:1.9,brightness:100,contrast:105,warmth:0});
 $('comfort-night').onclick=()=>preset({dark:true,brightness:75,contrast:100,warmth:5,wordTheme:'neutral'});
 $('comfort-focus').onclick=()=>{prefs.focusTools=true;applyPrefs();closePanels();fullscreen(true)};$('comfort-settings').onclick=()=>screen('settings');return;
 }
 comfortScreen(id);if(id!=='settings')return;
 const content=$('sheet').querySelector('.sheet-content');content.insertAdjacentHTML('afterbegin','<button class="comfort-card" id="comfort-open"><strong>Reading comfort presets</strong><small>Original · Larger text · Quiet evening · Full-page focus</small></button>');$('comfort-open').onclick=()=>screen('comfort');
 const theme=$('word-theme');theme.insertAdjacentHTML('beforeend',`<option value="warm" ${prefs.wordTheme==='warm'?'selected':''}>Warm parchment</option><option value="high-contrast" ${prefs.wordTheme==='high-contrast'?'selected':''}>High contrast monochrome</option>`);
 content.insertAdjacentHTML('beforeend',checkSetting('start-focus','Open in full-page focus',!!prefs.startFocus,'On the next launch. Floating controls remain available by default.')+checkSetting('focus-tools','Floating controls in focus view',prefs.focusTools!==false,'Safe-area menu, mode, bookmark and page controls; turn off for an unobstructed page. Tap the page or Android Back to return.')+checkSetting('swipe-pages','Swipe to change pages',prefs.swipes!==false,'Swipe right for next; left for previous. Disable if swipes interrupt reading.')+checkSetting('reading-guide-toggle','Reading line guide',!!prefs.guide,'A thin movable guide helps keep your place. It does not cover or change the text.')+rangeSetting('reading-guide-position','Guide position',clamp(prefs.guidePosition,10,90,50),10,90,5,'Position within the reading screen.')+rangeSetting('reading-contrast','Page contrast',clamp(prefs.contrast,90,140,100),90,140,5,'100 is the original. Applies only to the reading page.')+rangeSetting('reading-warmth','Paper warmth',clamp(prefs.warmth,0,30,0),0,30,5,'Optional warmer appearance. Keep at 0 for original Tajweed colours.'));
 [['start-focus','startFocus'],['focus-tools','focusTools'],['swipe-pages','swipes'],['reading-guide-toggle','guide']].forEach(([id,key])=>$(id).onchange=()=>{prefs[key]=$(id).checked;applyPrefs()});[['reading-guide-position','guidePosition'],['reading-contrast','contrast'],['reading-warmth','warmth']].forEach(([id,key])=>$(id).oninput=()=>{prefs[key]=Number($(id).value);applyPrefs()});
};
readerAppearance();if(prefs.startFocus)requestAnimationFrame(()=>fullscreen(true));
// Always provide a way out of an unobstructed focus view, including on iPhone.
reader.onclick=e=>{if(prefs.tapControls!==false||(immersive&&prefs.focusTools===false))originalReaderTap(e)};
const comfortFullscreen=fullscreen;fullscreen=function(on){comfortFullscreen(on);requestAnimationFrame(readerAppearance)};

window.addEventListener('resize',()=>requestAnimationFrame(readerAppearance));
// Margin-free native rendering + full-page layout is the default only for mode 3.
if(load('tm-mushaf-layout',0)<1){prefs.layouts={...(prefs.layouts||{}),plain:'fill'};prefs.pdfZooms={...(prefs.pdfZooms||{}),plain:100};prefs.plainFullscreen=true;prefs.plainMinimal=true;prefs.plainFooter=false;save('tm-mushaf-layout',1)}
const zoomForMode=()=>clamp(prefs.pdfZooms?.[mode],100,250,100);
let lastZoomPosition='',lastZoomStage=null;
function alignMagnifiedPage(){const stage=$('pdf-stage');const image=$('pdf-image');if(!stage||zoomForMode()===100||!image||image.dataset.page!==String(page)||!image.complete||!image.naturalWidth)return;const key=mode+':'+page+':'+zoomForMode();if(key!==lastZoomPosition||stage!==lastZoomStage){stage.scrollTop=0;stage.scrollLeft=stage.scrollWidth-stage.clientWidth;lastZoomPosition=key;lastZoomStage=stage}}
const mushafAppearance=readerAppearance;readerAppearance=function(){mushafAppearance();document.body.dataset.minimalMushaf=String(mode==='plain'&&prefs.plainMinimal!==false);document.body.dataset.hideMushafFooter=String(mode==='plain'&&prefs.plainFooter!==true);document.body.dataset.pdfEnlarged=String(isScan()&&zoomForMode()>100);document.documentElement.style.setProperty('--pdf-scale',zoomForMode()/100);requestAnimationFrame(alignMagnifiedPage)};
new MutationObserver(()=>requestAnimationFrame(alignMagnifiedPage)).observe($('page'),{childList:true,subtree:true,attributes:true,attributeFilter:['class','id']});
const mushafChangeMode=changeMode;changeMode=function(next){mushafChangeMode(next);if(next==='plain'&&prefs.plainFullscreen!==false)fullscreen(true);else if(immersive&&prefs.plainFullscreen!==false)fullscreen(false)};
// Scrolling a magnified PDF must pan the page rather than accidentally advance it.
reader.addEventListener('touchend',e=>{if(isScan()&&zoomForMode()>100&&touch){if(e.changedTouches.length&&Math.abs(e.changedTouches[0].clientX-touch.x)>15)suppressClickUntil=Date.now()+500;touch=null;e.stopImmediatePropagation()}},{capture:true,passive:true});
reader.onclick=e=>{if(prefs.tapControls!==false||(immersive&&(prefs.focusTools===false||(mode==='plain'&&prefs.plainMinimal!==false))))originalReaderTap(e)};
const mushafSettings=screen;screen=function(id){mushafSettings(id);if(id!=='settings')return;const content=$('sheet').querySelector('.sheet-content');
 content.insertAdjacentHTML('afterbegin',selectSetting('pdf-magnification','PDF magnification',[100,125,150,175,200,250].map(n=>[n,n+'%']),zoomForMode(),'Separate per PDF mode. Above 100%, scroll/pan from the Arabic right-hand side. Pinch zoom is also available.')+checkSetting('mushaf-fullscreen','Mode 3 full-page on opening',prefs.plainFullscreen!==false,'Trimmed page fills the safe reading area, matching a traditional Mushaf view.')+checkSetting('mushaf-minimal','Mode 3 minimal corner controls',prefs.plainMinimal!==false,'Only menu and bookmark remain. Tap the page to restore the full toolbar.')+checkSetting('mushaf-footer','Show mode 3 floating page controls',prefs.plainFooter===true,'Optional page badge and previous/next buttons. Hidden by default to keep the page clear.'));
 if(!isScan())$('pdf-magnification').closest('.setting').classList.add('hidden');$('pdf-magnification').onchange=()=>{prefs.pdfZooms={...(prefs.pdfZooms||{}),[mode]:Number($('pdf-magnification').value)};lastZoomPosition='';applyPrefs()};[['mushaf-fullscreen','plainFullscreen'],['mushaf-minimal','plainMinimal'],['mushaf-footer','plainFooter']].forEach(([id,key])=>$(id).onchange=()=>{prefs[key]=$(id).checked;applyPrefs()});
};
applyPrefs();if(mode==='plain'&&prefs.plainFullscreen!==false)requestAnimationFrame(()=>fullscreen(true));
