const LICENSE="MIT License\n\nCopyright (c) 2026 Abubakr Elmallah\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n";
'use strict';
const $=id=>document.getElementById(id),load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let page=Math.min(604,Math.max(1,Number(load('tm-page',1))||1)),marks=load('tm-bookmarks',[]),prefs=load('tm-settings',{meaning:true,dark:false,size:32,awake:false}),immersive=false,toastTimer;
// Shared rules use the printed Mode 3 legend; additional rules retain their own legend.
const printedTajweedColors={ikhfaaLight:'#009ac2',ikhfaaHeavy:'#009ac2',generalGhunnah:'#f58220',idghamGhunnah:'#007c3c',qalqalah:'#ed1620',iqlaab:'#39338c'};
const colors=Object.fromEntries(QURAN.rules.map(r=>[r.id,printedTajweedColors[r.id]||r.color]));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const digits=n=>String(n).replace(/\d/g,x=>'٠١٢٣٤٥٦٧٨٩'[x]);
function colored(v){let out='',end=0;for(const [lo,hi,rule] of v.ops){out+=esc(v.ar.slice(end,lo))+`<span style="color:${colors[rule]}" title="${esc(QURAN.rules.find(r=>r.id===rule).name)}">${esc(v.ar.slice(lo,hi))}</span>`;end=hi}return out+esc(v.ar.slice(end))}
function applyPrefs(){document.body.classList.toggle('dark',prefs.dark);document.body.classList.toggle('no-meaning',!prefs.meaning);document.documentElement.style.setProperty('--arabic',prefs.size+'px');if(window.Android)Android.awake(prefs.awake);save('tm-settings',prefs)}
function renderTajweed(){const verses=QURAN.pages[page],first=verses[0],last=verses.at(-1);$('top-label').textContent=QURAN.surahs[first.s-1].name+' · Juz '+first.j;let html=`<div class="page-top"><span>${esc(QURAN.surahs[first.s-1].name)}</span><span>Juz ${first.j}</span><span>${page} / 604</span></div>`;
 for(const v of verses){const s=QURAN.surahs[v.s-1];if(v.a===1){html+=`<div class="surah-heading"><strong lang="ar" dir="rtl">سُورَةُ ${esc(s.ar)}</strong><small>${s.id}. ${esc(s.name)} · ${s.count} ayahs</small></div>`;if(v.s!==1&&v.s!==9)html+=`<div class="bismillah" lang="ar" dir="rtl">${esc(QURAN.pages[1][0].ar)}</div>`}
 html+=`<div class="verse" id="v-${v.s}-${v.a}"><div class="arabic" lang="ar">${colored(v)} <span class="ayah-number">﴿${digits(v.a)}﴾</span></div><div class="translation"><span class="reference">${v.s}:${v.a}</span>${esc(v.en)}</div></div>`}
 $('page').innerHTML=html;$('page-button').textContent=`Page ${page} / 604`;$('next').disabled=page===604;$('previous').disabled=page===1;updateBookmark();save(pageKey(),page)}
function go(n,s,a){if(n<minPage()||n>maxPages())return;page=n;closePanels();render();window.scrollTo(0,0);if(s&&a){requestAnimationFrame(()=>{const el=$(`v-${s}-${a}`);if(el){el.scrollIntoView({block:'center'});el.classList.add('flash');setTimeout(()=>el.classList.remove('flash'),1600)}})}}
function updateBookmark(){$('bookmark').textContent=marks.includes(page)?'★':'☆';$('bookmark').setAttribute('aria-label',marks.includes(page)?'Remove page bookmark':'Bookmark page')}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),1800)}
function bookmark(){if(marks.includes(page)){marks=marks.filter(p=>p!==page);toast('Bookmark removed')}else{marks.push(page);marks.sort((a,b)=>a-b);toast('Page bookmarked')}save(bookmarkKey(),marks);updateBookmark()}
function fullscreen(on){immersive=on;document.body.classList.toggle('immersive',on);if(window.Android)Android.fullscreen(on);if(on)toast('Tap the page to show controls')}
function closePanels(){$('drawer').classList.add('hidden');$('shade').classList.add('hidden');$('sheet').classList.add('hidden')}
function drawer(){const rows=[['modes','▣','Reading mode'],['search','⌕','Find an ayah'],['history','↶','Recent reading'],['source','▤','Original PDF meanings'],['continue','↶',`Continue reading — ${page}`],['juz','▤','Juz (Para)'],['surahs','☷','Surahs'],['bookmarks','★','Bookmarks'],['jump','↗','Go to page'],['rules','◉','Tajweed colours'],['settings','⚙','Settings'],['about','ⓘ','About']];$('drawer').innerHTML=`<div class="drawer-head"><div class="art" lang="ar" dir="rtl">القرآن الكريم</div><h2>Tajweed & Meaning</h2><p>Read · Reflect · Remember</p></div>`+rows.map(([id,icon,text])=>`<button class="drawer-row" data-screen="${id}"><span class="icon">${icon}</span>${esc(text)}</button>`).join('')+'<div class="drawer-bottom">Complete Qur’an · Fully offline<br>No advertisements</div>';$('drawer').classList.remove('hidden');$('shade').classList.remove('hidden');$('drawer').querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>screen(b.dataset.screen))}
function openSheet(title,html){closePanels();$('sheet').innerHTML=`<div class="sheet-head"><button id="sheet-back" aria-label="Back to reader">‹</button><h2>${esc(title)}</h2></div><div class="sheet-content">${html}</div>`;$('sheet').classList.remove('hidden');$('sheet-back').onclick=closePanels}
function screen(id){if(id==='continue'){closePanels();return}if(id==='surahs'){openSheet('Surahs','<input id="search" class="search" placeholder="Find a Surah" aria-label="Search Surahs"><div id="surah-list"></div>');const list=()=>{$('surah-list').innerHTML=QURAN.surahs.filter(s=>(s.id+' '+s.name+' '+s.ar).toLowerCase().includes($('search').value.toLowerCase())).map(s=>`<button class="list-row" data-page="${s.page}" data-s="${s.id}" data-a="1"><span class="n">${s.id}</span><span class="names">${esc(s.name)}<small>${s.count} ayahs · Page ${s.page}</small></span><span class="ar-name" lang="ar">${esc(s.ar)}</span></button>`).join('');wireJumps()};$('search').oninput=list;list()}
 else if(id==='juz'){openSheet('Juz (Para)',QURAN.juz.map(j=>`<button class="list-row" data-page="${j.page}" data-s="${j.s}" data-a="${j.a}"><span class="n">${j.id}</span><span class="names">Juz ${j.id}<small>${esc(QURAN.surahs[j.s-1].name)} ${j.s}:${j.a} · Page ${j.page}</small></span><span>‹</span></button>`).join(''));wireJumps()}
 else if(id==='bookmarks'){openSheet('Bookmarks',marks.length?marks.map(p=>`<div class="list-row"><button class="names" data-page="${p}">Page ${p}<small>${esc(QURAN.surahs[QURAN.pages[p][0].s-1].name)}</small></button><button data-remove="${p}" aria-label="Remove bookmark">✕</button></div>`).join(''):'<p class="helper">Tap the star while reading to bookmark a page.</p>');wireJumps();$('sheet').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{marks=marks.filter(p=>p!==Number(b.dataset.remove));save(bookmarkKey(),marks);updateBookmark();screen('bookmarks')})}
 else if(id==='jump'){openSheet('Go to page','<p class="helper">Enter a page number from 1 to 604.</p><form id="jump-form"><input class="search" id="jump-number" type="number" min="1" max="604" required aria-label="Page number" value="'+page+'"><button class="action">Open page</button><p id="jump-error" class="helper"></p></form>');$('jump-form').onsubmit=e=>{e.preventDefault();const n=Number($('jump-number').value);if(Number.isInteger(n)&&n>=1&&n<=604)go(n);else $('jump-error').textContent='Please enter a whole number from 1 to 604.'}}
 else if(id==='rules'){openSheet('Tajweed colours','<p class="helper">Shared rules use Mode 3’s printed palette: Ikhfa blue, Ghunnah orange, Idgham green, Qalqalah red and Iqlab purple. Additional digital rules have their own colours below. Colours mark recitation rules in the Hafs text. Some rules apply when joining words. The colour layer is a learning aid; study recitation with a qualified teacher.</p>'+QURAN.rules.map(r=>`<div class="rule"><span class="dot" style="background:${colors[r.id]}"></span><div><strong>${esc(r.name)}</strong><p>${esc(r.description)}</p></div></div>`).join(''))}
 else if(id==='settings'){openSheet('Settings',`<div class="setting"><label for="meaning">English meaning<small>Hilali–Khan translation below each ayah</small></label><input id="meaning" type="checkbox" ${prefs.meaning?'checked':''}></div><div class="setting"><label for="dark">Dark mode</label><input id="dark" type="checkbox" ${prefs.dark?'checked':''}></div><div class="setting"><label for="awake">Keep screen awake<small>While the app is open</small></label><input id="awake" type="checkbox" ${prefs.awake?'checked':''}></div><div class="setting"><label for="size">Arabic text size</label><select id="size">${[30,32,36,40,46,52,60].map(s=>`<option value="${s}" ${prefs.size===s?'selected':''}>${s}</option>`).join('')}</select></div><p class="helper">Swipe right for the next page, left for the previous page. Tap the page to hide or show controls. Pinch to zoom.</p>`);['meaning','dark','awake'].forEach(k=>$(k).onchange=()=>{prefs[k]=$(k).checked;applyPrefs()});$('size').onchange=()=>{prefs.size=Number($('size').value);applyPrefs()}}
 else if(id==='about'){openSheet('About','<div class="about"><h3>Tajweed & Meaning · 1.7</h3><p>Four reading modes: original Arabic-English word-by-word PDF pages colourful Hafs Tajweed with Hilali–Khan English verse meanings, and Arabic-only colour-coded Tajweed. An original, offline reader made for Khalid.</p><p>Mode 2 uses reflowed text with 604-page navigation. Mode 3 uses the complete original 13-line Indo-Pak colour-coded Tajweed Mushaf, preserving printed letters, colours, line breaks and page numbers 4–850. The three mode-3 introductory cover/rules pages are skipped when reading.</p><h3>Word-by-word PDF</h3><p>Original 960 reading pages from the Haameem7 Arabic-English word-by-word Qur’an collection, linked to its all-in-one Internet Archive PDF. Original page images and translation are preserved. Word-by-word display trims blank outer scan margins per page while retaining the complete printed mint border, headings, page numbers and marginal text. Source: haameem7.wordpress.com/2023/01/07/quran-arabic-english-word-by-word-translation-juz-pdf/</p><h3>13-line printed Tajweed Mushaf</h3><p>Complete original scanned edition from Dawat-e-Hidayat: dawatehidayat.org/pages/13line_quran.html. Printed text and colours are preserved; only the outer blank PDF margins are removed from display. This edition uses its own printed Tajweed colour legend.</p><h3>Sources & attribution</h3><p>Arabic text and Uthmani font: King Fahd Glorious Qur’an Printing Complex (KFGQPC), via quran-data-kfgqpc and Quran-Tajweed-Engine.</p><p>Tajweed annotations and colour catalogue: Quran-Tajweed-Engine / Al-Islam, © Abubakr Elmallah, MIT. Precomputed annotations are a teaching layer with documented heuristic limitations, not a certified Mushaf.</p><p>English verse translation: Muhammad Muhsin Khan and Muhammad Taqi-ud-Din al-Hilali, via AlQuran Cloud. Translation conveys meanings and does not replace the Arabic Qur’an.</p><p>Source: github.com/TheAbubakrAbu/Quran-Tajweed-Engine<br>Translation: api.alquran.cloud</p><h3>MIT notice</h3><pre id="license"></pre><p>No login, advertisements or tracking. Web scans require a connection until saved for offline reading.</p></div>');$('license').textContent=LICENSE}
}
function wireJumps(){$('sheet').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(Number(b.dataset.page),Number(b.dataset.s),Number(b.dataset.a)))}
window.handleBack=()=>{if(!$('sheet').classList.contains('hidden')||!$('drawer').classList.contains('hidden')){closePanels();return true}if(immersive){fullscreen(false);return true}return false};
$('menu').onclick=drawer;$('shade').onclick=closePanels;$('bookmark').onclick=bookmark;$('full').onclick=()=>fullscreen(!immersive);$('page-button').onclick=()=>screen('jump');$('next').onclick=()=>go(page+1);$('previous').onclick=()=>go(page-1);
let suppressClickUntil=0;let touch=null;const reader=$('reader');reader.addEventListener('touchstart',e=>{touch=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY,time:Date.now()}:null},{passive:true});reader.addEventListener('touchend',e=>{if(!touch||e.changedTouches.length!==1)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if((!window.visualViewport||window.visualViewport.scale<1.05)&&Math.abs(dx)>90&&Math.abs(dx)>Math.abs(dy)*1.8&&Date.now()-touch.time<800){suppressClickUntil=Date.now()+500;go(page+(dx>0?1:-1));touch=null}},{passive:true});reader.onclick=e=>{if(Date.now()<suppressClickUntil)return;if(window.getSelection().toString())return;if(touch&&Date.now()-touch.time<800&&(Math.abs(e.clientX-touch.x)>15||Math.abs(e.clientY-touch.y)>15))return;fullscreen(!immersive)};
let mode=load('tm-mode','word');if(!['word','tajweed','plain','study','sixteen'].includes(mode))mode='word';
const maxPages=()=>mode==='sixteen'?SIXTEEN_NAV.total:mode==='study'?STUDY_NAV.total:mode==='word'?960:mode==='plain'?850:604;
const minPage=()=>mode==='plain'?4:1;
const isScan=()=>mode==='word'||mode==='plain'||mode==='study'||mode==='sixteen';
const imageKey=n=>mode+':'+n;
const bookmarkKey=()=>mode==='sixteen'?'tm-sixteen-bookmarks':mode==='study'?'tm-study-bookmarks':mode==='word'?'tm-word-bookmarks':mode==='plain'?'tm-plain-bookmarks':'tm-bookmarks';
function readModeState(){page=Math.max(minPage(),Math.min(maxPages(),Number(load(pageKey(),mode==='sixteen'?SIXTEEN_NAV.first:mode==='study'?STUDY_NAV.first:1))||1));marks=load(bookmarkKey(),[])}
readModeState();
function render(){document.body.classList.toggle('pdf-reading',mode==='word');if(mode==='tajweed'){renderTajweed();return}
 const surah=[...WORD_NAV.surahs].reverse().find(s=>s.page<=page);$('top-label').textContent='Word by word · Juz '+(Math.floor((page-1)/32)+1);$('page-button').textContent=`Page ${page} / 960`;$('next').disabled=page===960;$('previous').disabled=page===1;updateBookmark();save('tm-word-page',page);
 $('page').innerHTML='<div class="pdf-loading" id="pdf-loading">Opening page '+page+'…</div><img id="pdf-image" class="pdf-image hidden" alt="Arabic-English word-by-word Qur’an, page '+page+'">';
 if(window.Android&&Android.pdfPage)Android.pdfPage(page);else $('pdf-loading').textContent='PDF pages display in the installed Android app.';
}
window.receivePdf=(n,base64,error)=>{if(mode!=='word'||n!==page)return;const image=$('pdf-image'),loading=$('pdf-loading');if(!image||!loading)return;if(error){loading.textContent=error;return}image.onload=()=>{loading.classList.add('hidden');image.classList.remove('hidden')};image.onerror=()=>{loading.textContent='Unable to display this page. Try reopening it.'};image.src='data:image/jpeg;base64,'+base64};
function changeMode(next){if(next===mode){closePanels();return}mode=next;save('tm-mode',mode);readModeState();closePanels();render();window.scrollTo(0,0);toast(mode==='sixteen'?'16-line colour-coded Tajweed':mode==='study'?'Study the Noble Qur’an · Word for word':mode==='word'?'Word-by-word pages':mode==='plain'?'Tajweed · Arabic only':'Tajweed + Hilali–Khan meanings')}
const originalScreen=screen;
screen=function(id){if(id==='modes'){openSheet('Reading mode',`<button id="word-mode" class="mode-card ${mode==='word'?'active':''}"><strong>1. Word by word</strong><small>Original Arabic-English PDF pages · 960 pages<br>Meanings beneath each Arabic word</small></button><button id="tajweed-mode" class="mode-card ${mode==='tajweed'?'active':''}"><strong>Colourful Tajweed</strong><small>Colour-coded recitation text · 604-page navigation<br>English verse meanings</small></button><p class="helper">Saved pages work offline and remember their own page and bookmarks. Tajweed colours are available in Tajweed mode; the PDF keeps its original printed colours.</p>`);$('word-mode').onclick=()=>changeMode('word');$('tajweed-mode').onclick=()=>changeMode('tajweed');return}
 if(mode!=='word'){originalScreen(id);return}
 if(id==='continue'){closePanels();return}
 if(id==='surahs'){openSheet('Surahs','<input id="search" class="search" placeholder="Find a Surah" aria-label="Search Surahs"><div id="surah-list"></div>');const list=()=>{$('surah-list').innerHTML=WORD_NAV.surahs.filter(s=>(s.number+' '+s.name+' '+s.arabic).toLowerCase().includes($('search').value.toLowerCase())).map(s=>`<button class="list-row" data-page="${s.page}"><span class="n">${s.number}</span><span class="names">${esc(s.name)}<small>PDF page ${s.page}</small></span><span class="ar-name" lang="ar">${esc(s.arabic)}</span></button>`).join('');wireJumps()};$('search').oninput=list;list();return}
 if(id==='juz'){openSheet('Juz (Para)',WORD_NAV.juz.map(j=>`<button class="list-row" data-page="${j.page}"><span class="n">${j.number}</span><span class="names">${esc(j.name)}<small>PDF page ${j.page}</small></span><span>‹</span></button>`).join(''));wireJumps();return}
 if(id==='bookmarks'){openSheet('Bookmarks',marks.length?marks.map(p=>`<div class="list-row"><button class="names" data-page="${p}">PDF page ${p}<small>Word by word · Juz ${Math.floor((p-1)/32)+1}</small></button><button data-remove="${p}" aria-label="Remove bookmark">✕</button></div>`).join(''):'<p class="helper">Tap the star while reading to bookmark a PDF page.</p>');wireJumps();$('sheet').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{marks=marks.filter(p=>p!==Number(b.dataset.remove));save(bookmarkKey(),marks);updateBookmark();screen('bookmarks')});return}
 if(id==='jump'){openSheet('Go to page','<p class="helper">Enter a PDF page number from 1 to 960.</p><form id="jump-form"><input class="search" id="jump-number" type="number" min="1" max="960" required aria-label="Page number" value="'+page+'"><button class="action">Open page</button><p id="jump-error" class="helper"></p></form>');$('jump-form').onsubmit=e=>{e.preventDefault();const n=Number($('jump-number').value);if(Number.isInteger(n)&&n>=1&&n<=960)go(n);else $('jump-error').textContent='Please enter a whole number from 1 to 960.'};return}
 originalScreen(id);
 if(id==='settings'){const content=$('sheet').querySelector('.sheet-content');content.insertAdjacentHTML('afterbegin','<p class="helper">PDF pages keep their original text, translation and colours. Arabic text size and the English meaning toggle apply to Tajweed mode. Pinch to zoom the PDF.</p>')}
};

const pdfImages=new Map();let pdfVisiblePage=0,pdfDirection=1;
function pageKey(){return mode==='sixteen'?'tm-sixteen-page':mode==='study'?'tm-study-page':mode==='word'?'tm-word-page':mode==='plain'?'tm-plain-page':'tm-page'}
function recordHistory(){const key='tm-recent';let recent=load(key,[]).filter(v=>!(v.mode===mode&&v.page===page));recent.unshift({mode,page});save(key,recent.slice(0,15))}
function fitReadingPage(){if(isScan())return;const reader=$('reader');reader.classList.add('reading-overflow');document.documentElement.style.setProperty('--arabic',Math.max(30,prefs.size||36)+'px');document.documentElement.style.setProperty('--english',(prefs.englishSize||20)+'px')}

let pdfAnimation=0;
function removeScanImage(image){if(image?.parentElement?.classList.contains('sixteen-frame'))image.parentElement.remove();else image?.remove()}
function displayPdf(n,data){if(!isScan()||n!==page)return;const requestedMode=mode;const stage=$('pdf-stage');if(!stage)return;
 if($('pdf-image')?.dataset.page===String(n))return;
 stage.querySelectorAll('.pdf-pending').forEach(e=>e.remove());
 const incoming=new Image();incoming.className='pdf-image pdf-pending';incoming.alt=(mode==='sixteen'?'Original 16-line colour-coded Tajweed Qur’an, PDF page ':mode==='study'?'Study the Noble Qur’an, combined page ':mode==='plain'?'13-line colour-coded Tajweed Qur’an, page ':'Original Arabic-English word-by-word Qur’an, page ')+n;incoming.dataset.page=n;
 incoming.onload=async()=>{try{if(incoming.decode)await incoming.decode()}catch(e){}
  if(mode!==requestedMode||n!==page||!incoming.isConnected){incoming.remove();return}
  clearTimeout(pdfAnimation);stage.querySelectorAll('#pdf-previous').forEach(removeScanImage);
  if(requestedMode==='sixteen'&&typeof prepareSixteenFrame==='function')prepareSixteenFrame(incoming);
  const old=$('pdf-image');$('pdf-loading').classList.add('hidden');incoming.id='pdf-image';if(old){old.id='pdf-previous';old.style.transition='none';old.style.transform='translateX(0)'}
  if(old&&prefs.motion!==false&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const direction=pdfDirection;incoming.style.opacity='0';incoming.style.transform=`translateX(${-direction*12}px)`;incoming.classList.remove('pdf-pending');
   requestAnimationFrame(()=>requestAnimationFrame(()=>{if(!incoming.isConnected)return;incoming.style.transition='opacity 220ms ease-out, transform 220ms ease-out';incoming.style.opacity='1';incoming.style.transform='translateX(0)';old.style.transition='opacity 220ms ease-out';old.style.opacity='0';pdfAnimation=setTimeout(()=>removeScanImage(old),250)}));
  }else{incoming.classList.remove('pdf-pending');if(old)removeScanImage(old)}
  pdfVisiblePage=n;
 };incoming.onerror=()=>{incoming.remove();const loading=$('pdf-loading');if(mode!==requestedMode||n!==page||!loading)return;loading.innerHTML='This page could not open. Connect if it is not saved offline. <button id="retry-scan">Retry page</button>';loading.classList.remove('hidden');$('retry-scan').onclick=()=>render()};stage.appendChild(incoming);incoming.src=data.startsWith('pages/')||data.startsWith('data:')||data.startsWith('blob:')?data:'data:image/jpeg;base64,'+data;
}
function render(){document.body.classList.toggle('word-reading',mode==='word');document.body.classList.toggle('pdf-reading',isScan());document.body.classList.toggle('plain-reading',false);document.body.classList.toggle('fill-reading',mode==='tajweed');document.body.classList.toggle('pdf-proportions',prefs.pdfFit==='proportions');
 recordHistory();if(mode==='tajweed'){renderTajweed();$('reader').scrollTop=0;$('top-label').textContent=QURAN.surahs[QURAN.pages[page][0].s-1].name+' · Hilali–Khan meaning';save(pageKey(),page);requestAnimationFrame(fitReadingPage);document.fonts.ready.then(fitReadingPage);return}
 const meta=mode==='plain'?PLAIN_NAV.headers[page]:mode==='study'?STUDY_NAV.headers[page]:null;
 $('top-label').textContent=mode==='sixteen'?'16-line Tajweed · '+(page>=3&&page<=550?'Printed page '+(page-1):'Source page '+page):mode==='study'?(meta.intro?'Study Qur’an · Volume '+meta.volume+' introduction':'Study Qur’an · Vol '+meta.volume+' · Juz '+meta.j):mode==='plain'?'13-line Tajweed · Juz '+meta.j:'Word by word · Juz '+(Math.floor((page-1)/32)+1);$('page-button').textContent=`Page ${page} / ${maxPages()}`;$('next').disabled=page===maxPages();$('previous').disabled=page===minPage();updateBookmark();save(pageKey(),page);
 if(!$('pdf-stage')||$('pdf-stage').dataset.mode!==mode){pdfVisiblePage=0;$('page').innerHTML='<div id="pdf-stage" data-mode="'+mode+'"><div class="pdf-loading" id="pdf-loading">Opening Qur’an page…</div></div>'}
 pdfDirection=page>=pdfVisiblePage?1:-1;
 if(pdfImages.has(imageKey(page))){displayPdf(page,pdfImages.get(imageKey(page)));return}
 if(window.Android){if(mode==='sixteen'&&Android.sixteenPage)Android.sixteenPage(page);else if(mode==='study'&&Android.studyPage)Android.studyPage(page);else if(mode==='plain'&&Android.plainPage)Android.plainPage(page);else if(mode==='word'&&Android.pdfPage)Android.pdfPage(page)}else if(!$('pdf-image'))$('pdf-loading').textContent='PDF pages display in the installed Android app.';
}
function receiveScan(target,n,data,error){const key=target+':'+n;if(data){if(pdfImages.get(key)!==data)releaseScanUrl(pdfImages.get(key));pdfImages.delete(key);pdfImages.set(key,data);if(pdfImages.size>3){const oldest=pdfImages.keys().next().value;releaseScanUrl(pdfImages.get(oldest));pdfImages.delete(oldest)}}if(mode!==target||n!==page)return;if(error){$('pdf-loading').textContent=error;$('pdf-loading').classList.remove('hidden');return}displayPdf(n,data)}
window.receivePdf=(n,data,error)=>receiveScan('word',n,data,error);
window.receivePlainPdf=(n,data,error)=>receiveScan('plain',n,data,error);
window.receiveSixteenPdf=(n,data,error)=>receiveScan('sixteen',n,data,error);
window.receiveStudyPdf=(n,data,error)=>receiveScan('study',n,data,error);
window.turnPage=delta=>{if(!$('sheet').classList.contains('hidden')||!$('drawer').classList.contains('hidden'))return;go(page+delta)};
const baseApplyPrefs=applyPrefs;
applyPrefs=function(){baseApplyPrefs();document.body.dataset.wordTheme=prefs.wordTheme||'cream';document.body.classList.toggle('pdf-proportions',prefs.pdfFit==='proportions');if(window.Android&&Android.volumeKeys)Android.volumeKeys(!!prefs.volume);if(mode!=='word')requestAnimationFrame(fitReadingPage)};
const oldFullscreen=fullscreen;fullscreen=function(on){oldFullscreen(on);requestAnimationFrame(fitReadingPage)};
window.addEventListener('resize',()=>requestAnimationFrame(fitReadingPage));
const modeLabel=m=>m==='sixteen'?'16-line Tajweed':m==='study'?'Study the Noble Qur’an':m==='word'?'Word by word':m==='plain'?'Tajweed only':'Tajweed + Hilali–Khan';
const oldScreen=screen;
screen=function(id){
 if(id==='modes'){openSheet('Reading mode',`<button id="word-mode" class="mode-card ${mode==='word'?'active':''}"><strong>1. Word by word</strong><small>Original 960-page PDF from your link<br>Exact printed word meanings and page colours</small></button><button id="tajweed-mode" class="mode-card ${mode==='tajweed'?'active':''}"><strong>2. Colour Tajweed with meaning</strong><small>Colour-coded Hafs Arabic + Hilali–Khan verse translation<br>Complete Muhammad Muhsin Khan &amp; Muhammad Taqi-ud-Din al-Hilali translation</small></button><button id="plain-mode" class="mode-card ${mode==='plain'?'active':''}"><strong>3. Plain Qur’an with colour-coded Tajweed</strong><small>Original printed Indo-Pak Mushaf · 13 large lines<br>Same script and colours as your reference · available offline after saving</small></button>`);$('word-mode').onclick=()=>changeMode('word');$('tajweed-mode').onclick=()=>changeMode('tajweed');$('plain-mode').onclick=()=>changeMode('plain');return}
 if(id==='history'){const recent=load('tm-recent',[]);openSheet('Recent reading',recent.map((v,i)=>`<button class="list-row" data-history="${i}"><span class="n">${v.page}</span><span class="names">${modeLabel(v.mode)}<small>Page ${v.page}</small></span></button>`).join('')||'<p class="helper">Your recent pages will appear here.</p>');$('sheet').querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{const v=recent[Number(b.dataset.history)];changeMode(v.mode);go(v.page)});return}
 if(id==='search'){openSheet('Find an ayah','<input id="ayah-search" class="search" placeholder="Arabic, English or reference (e.g. 55:13)" aria-label="Find ayah"><p class="helper">Searches the Tajweed Arabic and Hilali–Khan verse translation. Results open in Tajweed mode.</p><div id="search-results"></div>');let timer;const normalize=s=>s.toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[أإآٱ]/g,'ا');$('ayah-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{const raw=$('ayah-search').value.trim(),query=normalize(raw);if(query.length<2){$('search-results').innerHTML='';return}let results=[];const ref=raw.match(/^(\d{1,3}):(\d{1,3})$/);for(let p=1;p<=604;p++){for(const v of QURAN.pages[p]){if(ref? v.s===Number(ref[1])&&v.a===Number(ref[2]):normalize(v.ar+' '+v.en).includes(query))results.push({p,v});if(results.length>=80)break}if(results.length>=80)break}$('search-results').innerHTML=results.map(({p,v})=>`<button class="list-row" data-result="${p}" data-s="${v.s}" data-a="${v.a}"><span class="names">${esc(QURAN.surahs[v.s-1].name)} ${v.s}:${v.a}<small>${esc(v.en.slice(0,120))}</small></span></button>`).join('')||'<p class="helper">No matching ayahs.</p>';$('sheet').querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{if(mode!=='tajweed')changeMode('tajweed');go(Number(b.dataset.result),Number(b.dataset.s),Number(b.dataset.a))})},180)};return}
 if(id==='source'){if(mode==='word'){closePanels();return}const surah=mode==='plain'?PLAIN_NAV.headers[page].s:QURAN.pages[page][0].s;const target=WORD_NAV.surahs.find(s=>s.number===surah);changeMode('word');go(target.page);toast('Original meanings · Surah start');return}
 oldScreen(id);
 if(id==='settings'){$('sheet').querySelector('.sheet-content').insertAdjacentHTML('beforeend',`<div class="setting"><label for="pdf-fit">PDF page layout<small>Fill screen uses the full height; original proportions preserves page shape.</small></label><select id="pdf-fit"><option value="fill" ${prefs.pdfFit!=='proportions'?'selected':''}>Fill screen</option><option value="proportions" ${prefs.pdfFit==='proportions'?'selected':''}>Original proportions</option></select></div><div class="setting"><label for="motion">Smooth page transitions</label><input type="checkbox" id="motion" ${prefs.motion!==false?'checked':''}></div><div class="setting"><label for="volume">Volume-button page turns<small>Volume down: next · Volume up: previous</small></label><input type="checkbox" id="volume" ${prefs.volume?'checked':''}></div>`);$('pdf-fit').onchange=()=>{prefs.pdfFit=$('pdf-fit').value;applyPrefs()};['motion','volume'].forEach(k=>$(k).onchange=()=>{prefs[k]=$(k).checked;applyPrefs()})}
};

const readableScreen=screen;
screen=function(id){readableScreen(id);if(id==='settings'){$('sheet').querySelector('.sheet-content').insertAdjacentHTML('afterbegin',`<div class="setting"><label for="english-size">English meaning size<small>Mode 2 keeps this size and scrolls; text never shrinks to fit a page.</small></label><select id="english-size">${[18,20,22,24,28,32].map(n=>`<option value="${n}" ${n===(prefs.englishSize||20)?'selected':''}>${n}</option>`).join('')}</select></div>`);$('english-size').onchange=()=>{prefs.englishSize=Number($('english-size').value);applyPrefs()}}};
const paletteScreen=screen;
screen=function(id){paletteScreen(id);if(id==='settings'){$('sheet').querySelector('.sheet-content').insertAdjacentHTML('afterbegin',`<div class="setting"><label for="word-theme">Word-by-word page colour<small>Mode 1 only · printed text and meanings stay unchanged.</small></label><select id="word-theme"><option value="cream" ${(prefs.wordTheme||'cream')==='cream'?'selected':''}>Soft cream</option><option value="neutral" ${prefs.wordTheme==='neutral'?'selected':''}>Neutral grey</option><option value="original" ${prefs.wordTheme==='original'?'selected':''}>Original green</option></select></div>`);$('word-theme').onchange=()=>{prefs.wordTheme=$('word-theme').value;applyPrefs()}}};
const scanScreen=screen;
screen=function(id){
 if(mode==='plain'){
  if(id==='surahs'){openSheet('Surahs','<input id="search" class="search" placeholder="Find a Surah" aria-label="Search Surahs"><div id="surah-list"></div>');const list=()=>{$('surah-list').innerHTML=PLAIN_NAV.surahs.filter(s=>(s.number+' '+s.name+' '+s.arabic).toLowerCase().includes($('search').value.toLowerCase())).map(s=>`<button class="list-row" data-page="${s.page}"><span class="n">${s.number}</span><span class="names">${esc(s.name)}<small>Printed page ${s.page}</small></span><span class="ar-name" lang="ar">${esc(s.arabic)}</span></button>`).join('');wireJumps()};$('search').oninput=list;list();return}
  if(id==='juz'){openSheet('Juz (Para)',PLAIN_NAV.juz.map(j=>`<button class="list-row" data-page="${j.page}"><span class="n">${j.number}</span><span class="names">Juz ${j.number}<small>Printed page ${j.page}</small></span></button>`).join(''));wireJumps();return}
  if(id==='jump'){openSheet('Go to printed page',`<p class="helper">Printed Qur’an pages 4–850. The cover and rules pages precede Al-Fatihah.</p><form id="jump-form"><input class="search" id="jump-number" type="number" min="4" max="850" required value="${page}" aria-label="Printed page number"><button class="action">Open page</button><p id="jump-error" class="helper"></p></form>`);$('jump-form').onsubmit=e=>{e.preventDefault();const n=Number($('jump-number').value);if(Number.isInteger(n)&&n>=4&&n<=850)go(n);else $('jump-error').textContent='Enter a printed page from 4 to 850.'};return}
  if(id==='bookmarks'){openSheet('Bookmarks',marks.length?marks.map(p=>`<div class="list-row"><button class="names" data-page="${p}">Printed page ${p}<small>13-line colour-coded Tajweed</small></button><button data-remove="${p}" aria-label="Remove bookmark">✕</button></div>`).join(''):'<p class="helper">Tap the star to bookmark a printed page.</p>');wireJumps();$('sheet').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{marks=marks.filter(p=>p!==Number(b.dataset.remove));save(bookmarkKey(),marks);updateBookmark();screen('bookmarks')});return}
  if(id==='rules'){openSheet('Printed Tajweed colours','<p class="helper">The same colour legend printed in this edition.</p><img src="plain-rules.jpg" style="width:100%;height:auto" alt="Original printed English Tajweed colour legend">');return}
 }
 scanScreen(id);
};
if(load('tm-plain-edition',0)<14){save('tm-plain-reflow-page',load('tm-plain-page',1));save('tm-plain-reflow-bookmarks',load('tm-plain-bookmarks',[]));save('tm-plain-page',4);save('tm-plain-bookmarks',[]);save('tm-plain-edition',14);save('tm-recent',load('tm-recent',[]).filter(v=>v.mode!=='plain'));readModeState()}

if(load('tm-readable-fonts',0)<16){prefs.size=Math.max(36,prefs.size||36);prefs.englishSize=20;save('tm-readable-fonts',16)}
// Migrate older layouts once, including a saved original-proportions setting.
if(load('tm-layout-version',0)<13){prefs.pdfFit='fill';prefs.motion=true;save('tm-layout-version',13)}
$('top-label').onclick=()=>screen('modes');$('top-label').setAttribute('role','button');$('top-label').setAttribute('tabindex','0');$('top-label').setAttribute('aria-label','Choose one of five reading modes');$('top-label').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();screen('modes')}};
applyPrefs();render();
