'use strict';
let webWorkerReady,offlineStartupError=null;
async function ensureOfflineReady(){
 if(!('serviceWorker' in navigator)||!('caches' in window)||!isSecureContext)throw new DOMException('Offline storage is unavailable in this browser.','SecurityError');
 const registration=await navigator.serviceWorker.register('./sw.js?v=11',{updateViaCache:'none'});
 const worker=registration.installing||registration.waiting;
 if(worker&&worker.state!=='activated')await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{worker.removeEventListener('statechange',changed);reject(Error('Setup took too long; saved files are kept.'))},45000);function changed(){if(worker.state==='activated'){clearTimeout(timeout);worker.removeEventListener('statechange',changed);resolve()}else if(worker.state==='redundant'){clearTimeout(timeout);worker.removeEventListener('statechange',changed);reject(Error('App resources could not be saved.'))}}worker.addEventListener('statechange',changed);changed()});
 if(!registration.active)throw Error('The offline reader is still starting. Retry setup.');
 const shell=await caches.open('quran-shell-v11');for(const file of ['index.html','data.js?v=11','web-upgrade.js?v=11','fonts/IndoPak.otf'])if(!await shell.match(file))throw Error('App download is incomplete. Retry setup while online.');
 offlineStartupError=null;return registration;
}
webWorkerReady=ensureOfflineReady().catch(e=>{offlineStartupError=e;return null});
const PAGE_CACHE='quran-pages-v1';let offlineJob=null;
const scanUrl=(m,n)=>m==='study'?studyScanUrl(n):`pages/${m}-${n}.${SCANS[m][n-1].ext}`;
function downloadRange(kind){if(kind==='all')return [['word',1,960],['plain',1,850],['study',1,STUDY_NAV.total],['sixteen',1,SIXTEEN_NAV.total]];if(mode==='tajweed')return [];if(kind==='mode')return [[mode,1,maxPages()]];const nav=mode==='sixteen'?SIXTEEN_NAV:mode==='study'?STUDY_NAV:mode==='word'?WORD_NAV:PLAIN_NAV,list=kind==='surah'?nav.surahs:nav.juz;const current=[...list].reverse().find(s=>s.page<=page)||list[0],index=list.indexOf(current),end=list[index+1]?.page||(mode==='sixteen'?SIXTEEN_NAV.quranLast:maxPages())+1;return [[mode,current.page,Math.max(current.page,mode==='sixteen'&&kind==='surah'?Math.min(end,SIXTEEN_NAV.quranLast):end-1)]]}
async function offlineOverview(){const cache=await caches.open(PAGE_CACHE),keys=await cache.keys(),saved={word:0,plain:0,study:0,sixteen:0};for(const k of keys){const match=new URL(k.url).pathname.match(/\/pages\/(word|plain|study|sixteen)-\d+\./);if(match)saved[match[1]]++}return saved}
function offlineProgress(){const text=$('offline-status'),bar=$('offline-progress');if(!text||!offlineJob)return;text.textContent=offlineJob.message||`Saved ${offlineJob.done} of ${offlineJob.total} selected pages. Keep the app open.`;if(bar){bar.max=offlineJob.total||1;bar.value=offlineJob.done}}
async function startOfflineDownload(kind){
 if(offlineJob?.running)return;
 const queue=downloadRange(kind).flatMap(([m,a,b])=>Array.from({length:b-a+1},(_,i)=>[m,a+i]));
 const job=offlineJob={running:true,done:0,total:queue.length,controller:new AbortController(),paused:false,message:''};offlineScreen();
 try{await ensureOfflineReady();if(queue.length===0){job.total=1;job.done=1}const cache=await caches.open(PAGE_CACHE);let index=0;
 const worker=async()=>{while(index<queue.length&&!job.controller.signal.aborted){const [m,n]=queue[index++],url=scanUrl(m,n);if(!await cache.match(url)){let response;for(let attempt=0;attempt<3;attempt++){try{response=m==='word'?await wordPageResponse(n,{signal:job.controller.signal}):await fetch(url,{signal:job.controller.signal});if(!response.ok||!response.headers.get('content-type')?.startsWith('image/'))throw Error('Could not download a page. Check your connection.');break}catch(e){if(job.controller.signal.aborted||attempt===2)throw e}}await cache.put(url,response)}job.done++;offlineProgress()}};
 let firstError;const guarded=()=>worker().catch(e=>{firstError??=e;job.controller.abort();throw e});await Promise.allSettled([guarded(),guarded()]);if(firstError)throw firstError;job.message=job.paused?'Paused. Saved pages are kept. Select the same download to resume.':queue.length===0?'Mode 2 saved: all 604 pages, Arabic fonts and original meanings.':'Selected pages saved. Browser storage may still be cleared by your device.';await navigator.storage?.persist?.();
 }catch(e){job.message=job.paused?'Paused. Saved pages are kept.':e.name==='QuotaExceededError'?'Storage is full. Saved pages are kept; free space or choose a smaller download.':e.message;job.controller.abort()}
 finally{job.running=false;offlineProgress();const pause=$('cancel-download');if(pause)pause.classList.add('hidden');document.querySelectorAll('[data-download]').forEach(b=>b.disabled=false);await updateOfflineCounts()}
}
async function updateOfflineCounts(){const node=$('offline-counts');if(!node)return;try{const saved=await offlineOverview(),estimate=await navigator.storage?.estimate?.();if(node.isConnected)node.textContent=`Word by word: ${saved.word}/960 pages · Plain Tajweed: ${saved.plain}/850 pages · Study Qur’an: ${saved.study}/${STUDY_NAV.total} pages · 16-line Tajweed: ${saved.sixteen}/${SIXTEEN_NAV.total} pages.`+(estimate?.quota?` Browser storage: ${Math.round((estimate.usage||0)/1048576)} MB used of ${Math.round(estimate.quota/1048576)} MB quota.`:'')}catch{node.textContent='Saved-page counts are unavailable.'}}
function offlineScreen(){openSheet('Offline reading',`<p class="helper">Mode 2 text and meanings are saved with the app. Choose how much to save for the scanned modes. Downloads resume by skipping saved pages.</p><p id="offline-counts" class="helper">Checking saved pages…</p><p id="offline-status" role="status" aria-live="polite"></p><progress id="offline-progress" max="1" value="0" aria-label="Download progress"></progress><div class="tools-actions">${mode!=='tajweed'?'<button data-download="surah">Save current Surah</button><button data-download="juz">Save current Juz</button><button data-download="mode">Save this reading mode</button>':''}<button class="action" data-download="all">Save all scanned modes · about ${Math.ceil(210+(STUDY_PDF.pageBytes+SIXTEEN_NAV.pageBytes)/1048576)} MB</button><button id="cancel-download" ${offlineJob?.running?'':'class="hidden"'}>Pause download</button></div><p class="helper">Keep the app open until finished. Safari may remove offline files when storage is low. Bookmarks and settings are stored separately on this device.</p>`);
 if(!('caches' in window)){$('offline-status').textContent='Offline storage is unavailable. Use Safari outside private browsing.';document.querySelectorAll('[data-download]').forEach(b=>b.disabled=true);return}document.querySelectorAll('[data-download]').forEach(b=>{b.disabled=!!offlineJob?.running;b.onclick=()=>startOfflineDownload(b.dataset.download)});$('cancel-download').onclick=()=>{if(offlineJob){offlineJob.paused=true;offlineJob.controller.abort()}};offlineProgress();updateOfflineCounts()}
const webDrawer=drawer;drawer=function(){webDrawer();const bottom=$('drawer').querySelector('.drawer-bottom');bottom.innerHTML='Complete Qur’an · Save pages for offline reading<br>No advertisements';bottom.insertAdjacentHTML('beforebegin','<button class="drawer-row" id="web-offline"><span class="icon">↓</span>Save for offline reading</button>');$('web-offline').onclick=offlineScreen};
$('menu').onclick=drawer;if($('focus-menu'))$('focus-menu').onclick=drawer;
if(!navigator.standalone&&!matchMedia('(display-mode: standalone)').matches&&!load('tm-install-tip',false)){const tip=document.createElement('div');tip.id='install-tip';tip.innerHTML='<button aria-label="Dismiss installation tip">×</button><strong>Read from your Home Screen</strong><br>On iPad or iPhone: open in Safari, tap Share, then Add to Home Screen.';document.body.appendChild(tip);tip.querySelector('button').onclick=()=>{save('tm-install-tip',true);tip.remove()}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&prefs.awake)Android.awake(true)});
const browserScreen=screen;screen=function(id){browserScreen(id);if(id==='settings'){for(const id of ['word-quality','volume']){const control=$(id);if(control)control.closest('.setting').classList.add('hidden')}}};

// Save the reading position before adopting a newer offline shell.
let previousController=navigator.serviceWorker?.controller,readerUpdatePending=false;
if('serviceWorker' in navigator)navigator.serviceWorker.addEventListener('controllerchange',()=>{const next=navigator.serviceWorker.controller;if(!previousController){previousController=next;return}if(next===previousController||readerUpdatePending)return;previousController=next;readerUpdatePending=true;if(offlineJob?.running){readerUpdatePending=false;return}try{if(sessionStorage.getItem('tm-shell-reloaded')==='11')return;sessionStorage.setItem('tm-shell-reloaded','11')}catch{}if(typeof rememberPosition==='function')rememberPosition();location.reload()});
