'use strict';
// Web-only reader improvements. Qur'an text, translation and scan files stay unchanged.
const readerModes=[["madina", "1 · Madina Mushaf · 15 lines"], ["word", "2 · Word by word full page translation"], ["tajweed", "3 · Ayat by ayat Quran with meaning"], ["study", "4 · Word to word Quran with meaning"], ["plain", "5 · 13-line colour-coded Tajweed"], ["fifteen", "6 · 15-line colour-coded Tajweed"], ["sixteen", "7 · 16-line colour-coded Tajweed"]];
if(!load('tm-indopak-style',false)){prefs.arabicStyle='indopak';prefs.readingLine=Math.max(2.4,prefs.readingLine||1.9);prefs.size=Math.max(40,prefs.size||36);save('tm-indopak-style',true)}
const improvedAppearance=readerAppearance;readerAppearance=function(){improvedAppearance();document.body.dataset.arabicStyle=prefs.arabicStyle||'indopak';document.body.dataset.ayahNumbers=String(prefs.ayahNumbers!==false);document.body.dataset.ayahActions=String(prefs.ayahActions!==false)};
const improvedBookmark=updateBookmark;updateBookmark=function(){improvedBookmark();for(const id of ['bookmark','focus-bookmark']){const b=$(id);if(!b)continue;const selected=marks.includes(page);b.setAttribute('aria-pressed',String(selected));b.title=selected?'Saved page · tap to remove':'Save this page';b.classList.toggle('is-saved',selected)}};
const priorAyahDecoration=decorateAyahs;decorateAyahs=function(){priorAyahDecoration();document.querySelectorAll('.verse').forEach(node=>{const [,s,a]=node.id.split('-').map(Number),saved=ayahMarks().some(v=>v.s===s&&v.a===a);node.classList.toggle('saved-ayah',saved);const b=node.querySelector('.ayah-actions button');if(b){const label=saved?'★ Saved '+s+':'+a:'☆ Save ayah '+s+':'+a;if(b.textContent!==label)b.textContent=label;b.setAttribute('aria-pressed',String(saved))}})};
const earlierToggleAyah=toggleAyahMark;toggleAyahMark=function(s,a){earlierToggleAyah(s,a);decorateAyahs()};
const earlierRender=render;let animatedPage=mode+':'+page;render=function(){const changed=animatedPage!==mode+':'+page;earlierRender();if(mode==='tajweed'&&changed&&prefs.motion!==false&&!matchMedia('(prefers-reduced-motion: reduce)').matches)$('page').animate([{opacity:.35,transform:'translateX(12px)'},{opacity:1,transform:'translateX(0)'}],{duration:220,easing:'ease-out'});animatedPage=mode+':'+page;updateBookmark()};
let settingsTab=null;
function arrangeModeSettings(){
 const content=$('sheet').querySelector('.sheet-content');content.insertAdjacentHTML('beforeend',selectSetting('arabic-style','Arabic font · Mode 3',[['indopak','Indo-Pak'],['uthmani','Original Uthmani']],prefs.arabicStyle||'indopak','Changes the typeface only. Arabic text and Hilali–Khan meanings remain unchanged.')+checkSetting('ayah-numbers','Show ayah numbers',prefs.ayahNumbers!==false,'Keep the verse number visible beside the Arabic.')+checkSetting('ayah-actions','Show Save ayah buttons',prefs.ayahActions!==false,'Saved ayahs keep the Surah and ayah number.')+'<button id="settings-saved-ayahs" class="action">Open saved ayahs</button><button id="settings-downloads" class="action">Downloads & offline reading</button>');
 $('arabic-style').onchange=()=>{prefs.arabicStyle=$('arabic-style').value;if(prefs.arabicStyle==='indopak')prefs.readingLine=Math.max(2.4,prefs.readingLine||1.9);applyPrefs()};for(const [id,key]of [['ayah-numbers','ayahNumbers'],['ayah-actions','ayahActions']])$(id).onchange=()=>{prefs[key]=$(id).checked;applyPrefs();decorateAyahs()};$('settings-saved-ayahs').onclick=showAyahMarks;$('settings-downloads').onclick=offlineScreen;
 const chosen=settingsTab==='general'?'general':mode;settingsTab=chosen;
 const nav=document.createElement('nav');nav.className='mode-settings-tabs';nav.setAttribute('aria-label','Settings by reading mode');
 for(const [m,label]of [...readerModes,['general','General']]){const b=document.createElement('button');b.textContent=label;b.dataset.settingsMode=m;b.setAttribute('aria-current',chosen===m?'page':'false');b.onclick=()=>{settingsTab=m;if(m!=='general'&&mode!==m)changeMode(m);screen('settings')};nav.appendChild(b)}content.prepend(nav);
 const scanIds=['pdf-fit','pdf-magnification'];const modeIds={word:[...scanIds,'word-theme','word-quality','word-edges','word-study','study-step','word-fullscreen'],tajweed:['arabic-style','meaning','size','english-size','reading-line','meaning-line','ayah-numbers','ayah-actions','settings-saved-ayahs'],plain:[...scanIds,'mushaf-fullscreen','mushaf-minimal','mushaf-footer'],study:scanIds,sixteen:scanIds,fifteen:scanIds,madina:scanIds};
 const specific=new Set(Object.values(modeIds).flat()),newRows=new Map();for(const id of ['arabic-style','ayah-numbers','ayah-actions','settings-saved-ayahs','settings-downloads']){const node=$(id).closest('.setting')||$(id);node.dataset.settingId=id;node.classList.add('searchable-setting');newRows.set(id,node)}
 const box=document.createElement('details');box.className='settings-section';box.open=true;box.innerHTML='<summary>'+esc(chosen==='general'?'General settings':readerModes.find(m=>m[0]===mode)[1])+'</summary><div class="settings-section-body"></div>';
 if(chosen!=='general')for(const id of modeIds[mode]){const node=newRows.get(id)||$(id)?.closest('.setting')||$(id);if(node){node.classList.remove('hidden');box.lastElementChild.appendChild(node)}}
 box.lastElementChild.appendChild($('settings-downloads'));content.insertBefore(box,nav.nextSibling);
 content.querySelectorAll('.settings-section').forEach(section=>{if(section===box)return;section.querySelectorAll('.searchable-setting').forEach(row=>{if(specific.has(row.dataset.settingId))row.remove()});if(!section.querySelector('.searchable-setting'))section.remove();else section.hidden=chosen!=='general'});
 for(const node of newRows.values())if(node.parentElement===content)node.remove();
 const hint=content.querySelector('p.helper');if(hint)hint.textContent='Choose a mode above for its settings. General contains shared colours, page turns, accessibility and backup. Settings save automatically.';
}
const upgradedScreen=screen;screen=function(id){if(id==='settings'&&$('sheet').classList.contains('hidden'))settingsTab=null;upgradedScreen(id);if(id==='settings')arrangeModeSettings();if(id==='about')$('sheet').querySelector('.sheet-content').insertAdjacentHTML('beforeend','<h3>Indo-Pak typeface</h3><p>DigitalKhatt IndoPak by DigitalKhatt, based on the 13-line Quraan Al Majeed Mushaf, supplied through Tarteel QUL. SIL Open Font License 1.1. The original Arabic text, Tajweed annotations and Hilali–Khan meanings are unchanged.</p>')};
const improvedBackup=validateBackup;validateBackup=function(b){improvedBackup(b);const p=b.data['tm-settings'];if(p){if(p.arabicStyle!=null&&!['indopak','uthmani'].includes(p.arabicStyle))throw Error('Invalid Arabic style');for(const k of ['ayahNumbers','ayahActions'])if(p[k]!=null&&typeof p[k]!=='boolean')throw Error('Invalid ayah setting')}};
applyPrefs();decorateAyahs();updateBookmark();
// Explain source colours without applying unverified Tajweed markings to scans.
const sourceColourScreen=screen;screen=function(id){
 if(id==='rules'&&(mode==='word'||mode==='study')){
  openSheet('Printed page colours',`<p class="helper">${mode==='study'?'Mode 4 preserves the original study edition’s printed colours, including its grammar categories.':'Mode 2 preserves the original word-by-word edition’s printed page colours.'} These scans do not contain the same Tajweed annotations as Mode 5. Changing their letters’ colours would require a verified annotated edition.</p><p class="helper">Use Mode 5 for the original printed Tajweed pages, or Mode 3 for digital Tajweed with meanings. Shared digital rules follow this printed legend; additional digital rules are listed in Mode 3.</p><img src="plain-rules.jpg" style="width:100%;height:auto" alt="Mode 5 original printed Tajweed colour legend">`);return
 }
 sourceColourScreen(id)
};
