'use strict';
let offlineTarget=mode,offlineSettingUp=false;
const modeTotal={word:960,tajweed:604,plain:850,study:STUDY_NAV.total,sixteen:SIXTEEN_NAV.total,fifteen:FIFTEEN_NAV.total,madina:MADINA_NAV.total};
const originalDownloadRange=downloadRange;downloadRange=function(kind){if(kind==='page')return offlineTarget==='tajweed'?[]:[[offlineTarget,offlineTarget===mode?page:clamp(load(offlineTarget==='madina'?'tm-madina-page':offlineTarget==='fifteen'?'tm-fifteen-page':offlineTarget==='sixteen'?'tm-sixteen-page':offlineTarget==='study'?'tm-study-page':offlineTarget==='plain'?'tm-plain-page':'tm-word-page',offlineTarget==='madina'?MADINA_NAV.first:offlineTarget==='fifteen'?30:offlineTarget==='sixteen'?3:offlineTarget==='plain'?4:offlineTarget==='study'?13:1),1,modeTotal[offlineTarget],1),offlineTarget===mode?page:clamp(load(offlineTarget==='madina'?'tm-madina-page':offlineTarget==='fifteen'?'tm-fifteen-page':offlineTarget==='sixteen'?'tm-sixteen-page':offlineTarget==='study'?'tm-study-page':offlineTarget==='plain'?'tm-plain-page':'tm-word-page',offlineTarget==='madina'?MADINA_NAV.first:offlineTarget==='fifteen'?30:offlineTarget==='sixteen'?3:offlineTarget==='plain'?4:offlineTarget==='study'?13:1),1,modeTotal[offlineTarget],1)]];if(kind==='mode')return offlineTarget==='tajweed'?[]:[[offlineTarget,1,modeTotal[offlineTarget]]];return originalDownloadRange(kind)};
function offlineErrorText(e){if(e.name==='QuotaExceededError'||/quota/i.test(e.message))return 'Device storage is full. Existing downloads and bookmarks are kept. Free some storage and try again.';if(e.name==='SecurityError'||!isSecureContext)return 'Open this app in Safari or Chrome using its https link, outside private browsing, then try setup again.';return 'Offline setup could not finish. Check your connection and tap Retry setup. '+(e.message||'')}
async function retryOfflineSetup(){if(offlineSettingUp)return;offlineSettingUp=true;const n=$('offline-health');if(n)n.textContent='Preparing offline app and Mode 3 text…';try{await ensureOfflineReady();if(n?.isConnected)n.textContent='Offline app ready · all 604 Mode 3 pages, Arabic fonts and meanings saved.';await updateOfflineCounts()}catch(e){if(n?.isConnected)n.textContent=offlineErrorText(e)}finally{offlineSettingUp=false}}
function startModeDownload(target,kind){if(offlineJob?.running)return;offlineTarget=target;return startOfflineDownload(kind)}
const previousOfflineScreen=offlineScreen;offlineScreen=function(){
 openSheet('Downloads & offline reading','<p class="helper">First prepare the app and Mode 3. Then download any scanned mode, or smaller selections from your current mode. Saved pages are skipped when resuming.</p><p id="offline-health" class="offline-health" role="status">Checking offline setup…</p><button id="offline-retry">Retry setup / check readiness</button><p id="offline-counts" class="helper"></p><p id="offline-status" role="status" aria-live="polite"></p><progress id="offline-progress" max="1" value="0" aria-label="Download progress"></progress>'+readerModes.map(([m,label])=>'<section class="download-mode-row"><strong>'+esc(label)+'</strong><small id="download-count-'+m+'">'+(m==='tajweed'?'Text and meanings are included in the offline app.':modeTotal[m]+' scanned pages')+'</small><div class="tools-actions"><button data-mode-download="'+m+'">'+(m==='tajweed'?'Save Mode 3 for offline':'Download complete mode')+'</button>'+(m===mode&&m!=='tajweed'?'<button data-small-download="page">Save current page</button><button data-small-download="surah">Save current Surah</button><button data-small-download="juz">Save current Juz</button>':'')+'</div></section>').join('')+'<div class="tools-actions"><button class="action" data-download="all">Download all seven modes · about '+Math.ceil(210+(STUDY_PDF.pageBytes+SIXTEEN_NAV.pageBytes+FIFTEEN_NAV.pageBytes+MADINA_NAV.pageBytes)/1048576)+' MB of scans</button><button id="cancel-download" '+(offlineJob?.running?'':'class="hidden"')+'>Pause download</button><button id="offline-pdf">Mode 4 · download complete PDF</button></div><p class="helper">Keep the app open during downloads. Offline files are stored on this device. Safari can remove them if storage runs low; your bookmarks are separate.</p>');
 $('offline-retry').onclick=retryOfflineSetup;$('offline-pdf').onclick=downloadStudyPdf;$('cancel-download').onclick=()=>{if(offlineJob){offlineJob.paused=true;offlineJob.controller.abort()}};
 document.querySelectorAll('[data-mode-download]').forEach(b=>{b.disabled=!!offlineJob?.running;b.onclick=()=>startModeDownload(b.dataset.modeDownload,'mode')});document.querySelectorAll('[data-small-download]').forEach(b=>{b.disabled=!!offlineJob?.running;b.onclick=()=>startModeDownload(mode,b.dataset.smallDownload)});document.querySelector('[data-download="all"]').onclick=()=>startModeDownload(mode,'all');offlineProgress();updateOfflineCounts();if(!offlineJob?.running)retryOfflineSetup();
};
const previousCounts=updateOfflineCounts;updateOfflineCounts=async function(){await previousCounts();try{const saved=await offlineOverview();for(const [m]of readerModes){const n=$('download-count-'+m);if(n)n.textContent=m==='tajweed'?(await caches.has('quran-shell-v16')?'604 / 604 text pages saved with the app':'Prepare offline app to save all 604 text pages'):saved[m]+' / '+modeTotal[m]+' pages saved'}document.querySelectorAll('[data-mode-download],[data-small-download],[data-download]').forEach(b=>b.disabled=!!offlineJob?.running)}catch{}};
